/*
 * ClientView.java
 */

package client;

import org.jdesktop.application.Action;
import org.jdesktop.application.ResourceMap;
import org.jdesktop.application.SingleFrameApplication;
import org.jdesktop.application.FrameView;
import org.jdesktop.application.TaskMonitor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import javax.swing.Icon;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;

/**
 * The application's main frame.
 */
public class ClientView extends FrameView {

    public ClientView(SingleFrameApplication app) {
        super(app);

        initComponents();

        // status bar initialization - message timeout, idle icon and busy animation, etc
        ResourceMap resourceMap = getResourceMap();
        int messageTimeout = resourceMap.getInteger("StatusBar.messageTimeout");
        messageTimer = new Timer(messageTimeout, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                statusMessageLabel.setText("");
            }
        });
        messageTimer.setRepeats(false);
        int busyAnimationRate = resourceMap.getInteger("StatusBar.busyAnimationRate");
        for (int i = 0; i < busyIcons.length; i++) {
            busyIcons[i] = resourceMap.getIcon("StatusBar.busyIcons[" + i + "]");
        }
        busyIconTimer = new Timer(busyAnimationRate, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                busyIconIndex = (busyIconIndex + 1) % busyIcons.length;
                statusAnimationLabel.setIcon(busyIcons[busyIconIndex]);
            }
        });
        idleIcon = resourceMap.getIcon("StatusBar.idleIcon");
        statusAnimationLabel.setIcon(idleIcon);
        progressBar.setVisible(false);

        // connecting action tasks to status bar via TaskMonitor
        TaskMonitor taskMonitor = new TaskMonitor(getApplication().getContext());
        taskMonitor.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                String propertyName = evt.getPropertyName();
                if ("started".equals(propertyName)) {
                    if (!busyIconTimer.isRunning()) {
                        statusAnimationLabel.setIcon(busyIcons[0]);
                        busyIconIndex = 0;
                        busyIconTimer.start();
                    }
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(true);
                } else if ("done".equals(propertyName)) {
                    busyIconTimer.stop();
                    statusAnimationLabel.setIcon(idleIcon);
                    progressBar.setVisible(false);
                    progressBar.setValue(0);
                } else if ("message".equals(propertyName)) {
                    String text = (String)(evt.getNewValue());
                    statusMessageLabel.setText((text == null) ? "" : text);
                    messageTimer.restart();
                } else if ("progress".equals(propertyName)) {
                    int value = (Integer)(evt.getNewValue());
                    progressBar.setVisible(true);
                    progressBar.setIndeterminate(false);
                    progressBar.setValue(value);
                }
            }
        });
    }

    @Action
    public void showAboutBox() {
        if (aboutBox == null) {
            JFrame mainFrame = ClientApp.getApplication().getMainFrame();
            aboutBox = new ClientAboutBox(mainFrame);
            aboutBox.setLocationRelativeTo(mainFrame);
        }
        ClientApp.getApplication().show(aboutBox);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        javax.swing.JMenu fileMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem exitMenuItem = new javax.swing.JMenuItem();
        javax.swing.JMenu helpMenu = new javax.swing.JMenu();
        javax.swing.JMenuItem aboutMenuItem = new javax.swing.JMenuItem();
        statusPanel = new javax.swing.JPanel();
        javax.swing.JSeparator statusPanelSeparator = new javax.swing.JSeparator();
        statusMessageLabel = new javax.swing.JLabel();
        statusAnimationLabel = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();
        jSplitPane1 = new javax.swing.JSplitPane();
        jTopPanel = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabelTenKhachSan = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelThoiGian = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jLeftPanel = new javax.swing.JPanel();
        jBtnXemPhong = new javax.swing.JButton();
        jBtnTimPhong = new javax.swing.JButton();
        jBtnThuePhong = new javax.swing.JButton();
        jBtnTraPhong = new javax.swing.JButton();
        jBtnThongKe = new javax.swing.JButton();
        jBtnSubmitXML = new javax.swing.JButton();
        jBtnCauHinh = new javax.swing.JButton();
        jRightPanel = new javax.swing.JPanel();
        jPaneXemChiTiet = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelHinhPhong_XemChiTiet = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelGiaTien_XemChiTiet = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnThoat_XemChiTiet = new javax.swing.JButton();
        jBtnCapNhat_XemChiTiet = new javax.swing.JButton();
        jBtnChinhSua_XemChiTiet = new javax.swing.JButton();
        jBtnThuePhong_XemChiTiet = new javax.swing.JButton();
        jPaneTimPhong = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jBtnThoat_TimPhong = new javax.swing.JButton();
        jBtnTimPhong_TimPhong = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        mainPanel.setName("mainPanel"); // NOI18N

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 249, Short.MAX_VALUE)
        );

        menuBar.setName("menuBar"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(ClientView.class);
        fileMenu.setText(resourceMap.getString("fileMenu.text")); // NOI18N
        fileMenu.setName("fileMenu"); // NOI18N

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getActionMap(ClientView.class, this);
        exitMenuItem.setAction(actionMap.get("quit")); // NOI18N
        exitMenuItem.setName("exitMenuItem"); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        helpMenu.setText(resourceMap.getString("helpMenu.text")); // NOI18N
        helpMenu.setName("helpMenu"); // NOI18N

        aboutMenuItem.setAction(actionMap.get("showAboutBox")); // NOI18N
        aboutMenuItem.setName("aboutMenuItem"); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        statusPanel.setName("statusPanel"); // NOI18N

        statusPanelSeparator.setName("statusPanelSeparator"); // NOI18N

        statusMessageLabel.setName("statusMessageLabel"); // NOI18N

        statusAnimationLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        statusAnimationLabel.setName("statusAnimationLabel"); // NOI18N

        progressBar.setName("progressBar"); // NOI18N

        javax.swing.GroupLayout statusPanelLayout = new javax.swing.GroupLayout(statusPanel);
        statusPanel.setLayout(statusPanelLayout);
        statusPanelLayout.setHorizontalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(statusPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusMessageLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 837, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusAnimationLabel)
                .addContainerGap())
        );
        statusPanelLayout.setVerticalGroup(
            statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statusPanelLayout.createSequentialGroup()
                .addComponent(statusPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusMessageLabel)
                    .addComponent(statusAnimationLabel)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setDoubleBuffered(true);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jTopPanel.setName("jTopPanel"); // NOI18N
        jTopPanel.setLayout(new java.awt.GridLayout(1, 3, 5, 5));

        jLabelLogo.setIcon(resourceMap.getIcon("jLabelLogo.icon")); // NOI18N
        jLabelLogo.setText(resourceMap.getString("jLabelLogo.text")); // NOI18N
        jLabelLogo.setDisabledIcon(resourceMap.getIcon("jLabelLogo.disabledIcon")); // NOI18N
        jLabelLogo.setDoubleBuffered(true);
        jLabelLogo.setEnabled(false);
        jLabelLogo.setName("jLabelLogo"); // NOI18N
        jTopPanel.add(jLabelLogo);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setName("jSeparator2"); // NOI18N
        jTopPanel.add(jSeparator2);

        jLabelTenKhachSan.setBackground(resourceMap.getColor("jLabelTenKhachSan.background")); // NOI18N
        jLabelTenKhachSan.setFont(resourceMap.getFont("jLabelTenKhachSan.font")); // NOI18N
        jLabelTenKhachSan.setForeground(resourceMap.getColor("jLabelTenKhachSan.foreground")); // NOI18N
        jLabelTenKhachSan.setText(resourceMap.getString("jLabelTenKhachSan.text")); // NOI18N
        jLabelTenKhachSan.setName("jLabelTenKhachSan"); // NOI18N
        jTopPanel.add(jLabelTenKhachSan);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N
        jTopPanel.add(jSeparator1);

        jLabelThoiGian.setText(resourceMap.getString("jLabelThoiGian.text")); // NOI18N
        jLabelThoiGian.setName("jLabelThoiGian"); // NOI18N
        jTopPanel.add(jLabelThoiGian);

        jSplitPane1.setLeftComponent(jTopPanel);

        jSplitPane2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSplitPane2.setName("jSplitPane2"); // NOI18N

        jLeftPanel.setName("jLeftPanel"); // NOI18N
        jLeftPanel.setLayout(new java.awt.GridLayout(7, 1, 5, 5));

        jBtnXemPhong.setText(resourceMap.getString("jBtnXemPhong.text")); // NOI18N
        jBtnXemPhong.setName("jBtnXemPhong"); // NOI18N
        jBtnXemPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnXemPhongMouseClicked(evt);
            }
        });
        jLeftPanel.add(jBtnXemPhong);

        jBtnTimPhong.setText(resourceMap.getString("jBtnTimPhong.text")); // NOI18N
        jBtnTimPhong.setName("jBtnTimPhong"); // NOI18N
        jBtnTimPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTimPhongMouseClicked(evt);
            }
        });
        jLeftPanel.add(jBtnTimPhong);

        jBtnThuePhong.setText(resourceMap.getString("jBtnThuePhong.text")); // NOI18N
        jBtnThuePhong.setName("jBtnThuePhong"); // NOI18N
        jBtnThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThuePhongMouseClicked(evt);
            }
        });
        jLeftPanel.add(jBtnThuePhong);

        jBtnTraPhong.setText(resourceMap.getString("jBtnTraPhong.text")); // NOI18N
        jBtnTraPhong.setName("jBtnTraPhong"); // NOI18N
        jBtnTraPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnTraPhongMouseClicked(evt);
            }
        });
        jLeftPanel.add(jBtnTraPhong);

        jBtnThongKe.setText(resourceMap.getString("jBtnThongKe.text")); // NOI18N
        jBtnThongKe.setName("jBtnThongKe"); // NOI18N
        jBtnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThongKeMouseClicked(evt);
            }
        });
        jLeftPanel.add(jBtnThongKe);

        jBtnSubmitXML.setText(resourceMap.getString("jBtnSubmitXML.text")); // NOI18N
        jBtnSubmitXML.setName("jBtnSubmitXML"); // NOI18N
        jBtnSubmitXML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnSubmitXMLMouseClicked(evt);
            }
        });
        jLeftPanel.add(jBtnSubmitXML);

        jBtnCauHinh.setText(resourceMap.getString("jBtnCauHinh.text")); // NOI18N
        jBtnCauHinh.setName("jBtnCauHinh"); // NOI18N
        jBtnCauHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnCauHinhMouseClicked(evt);
            }
        });
        jLeftPanel.add(jBtnCauHinh);

        jSplitPane2.setLeftComponent(jLeftPanel);

        jRightPanel.setName("jRightPanel"); // NOI18N

        javax.swing.GroupLayout jRightPanelLayout = new javax.swing.GroupLayout(jRightPanel);
        jRightPanel.setLayout(jRightPanelLayout);
        jRightPanelLayout.setHorizontalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 909, Short.MAX_VALUE)
        );
        jRightPanelLayout.setVerticalGroup(
            jRightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jRightPanel);

        jSplitPane1.setBottomComponent(jSplitPane2);

        jPaneXemChiTiet.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jPaneXemChiTiet.setName("jPaneXemChiTiet"); // NOI18N

        jSplitPane4.setName("jSplitPane4"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabelHinhPhong_XemChiTiet.setIcon(resourceMap.getIcon("jLabelHinhPhong_XemChiTiet.icon")); // NOI18N
        jLabelHinhPhong_XemChiTiet.setText(resourceMap.getString("jLabelHinhPhong_XemChiTiet.text")); // NOI18N
        jLabelHinhPhong_XemChiTiet.setName("jLabelHinhPhong_XemChiTiet"); // NOI18N
        jPanel2.add(jLabelHinhPhong_XemChiTiet);

        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 2));
        jSeparator3.setName("jSeparator3"); // NOI18N
        jPanel2.add(jSeparator3);

        jLabelGiaTien_XemChiTiet.setText(resourceMap.getString("jLabelGiaTien_XemChiTiet.text")); // NOI18N
        jLabelGiaTien_XemChiTiet.setName("jLabelGiaTien_XemChiTiet"); // NOI18N
        jPanel2.add(jLabelGiaTien_XemChiTiet);

        jSplitPane4.setLeftComponent(jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(3, 2));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel3.add(jLabel3);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel3.add(jLabel4);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel3.add(jLabel5);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel3.add(jLabel6);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel3.add(jLabel7);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel3.add(jLabel8);

        jSplitPane4.setRightComponent(jPanel3);

        jPaneXemChiTiet.setLeftComponent(jSplitPane4);

        jPanel1.setName("jPanel1"); // NOI18N

        jBtnThoat_XemChiTiet.setText(resourceMap.getString("jBtnThoat_XemChiTiet.text")); // NOI18N
        jBtnThoat_XemChiTiet.setName("jBtnThoat_XemChiTiet"); // NOI18N
        jBtnThoat_XemChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThoat_XemChiTietMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnThoat_XemChiTiet);

        jBtnCapNhat_XemChiTiet.setText(resourceMap.getString("jBtnCapNhat_XemChiTiet.text")); // NOI18N
        jBtnCapNhat_XemChiTiet.setEnabled(false);
        jBtnCapNhat_XemChiTiet.setName("jBtnCapNhat_XemChiTiet"); // NOI18N
        jPanel1.add(jBtnCapNhat_XemChiTiet);

        jBtnChinhSua_XemChiTiet.setText(resourceMap.getString("jBtnChinhSua_XemChiTiet.text")); // NOI18N
        jBtnChinhSua_XemChiTiet.setName("jBtnChinhSua_XemChiTiet"); // NOI18N
        jPanel1.add(jBtnChinhSua_XemChiTiet);

        jBtnThuePhong_XemChiTiet.setText(resourceMap.getString("jBtnThuePhong_XemChiTiet.text")); // NOI18N
        jBtnThuePhong_XemChiTiet.setName("jBtnThuePhong_XemChiTiet"); // NOI18N
        jPanel1.add(jBtnThuePhong_XemChiTiet);

        jPaneXemChiTiet.setRightComponent(jPanel1);

        jPaneTimPhong.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jPaneTimPhong.setName("jPaneTimPhong"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(2, 2));

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jPanel4.add(jLabel2);

        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jPanel4.add(jTextField1);

        jBtnThoat_TimPhong.setText(resourceMap.getString("jBtnThoat_TimPhong.text")); // NOI18N
        jBtnThoat_TimPhong.setName("jBtnThoat_TimPhong"); // NOI18N
        jPanel4.add(jBtnThoat_TimPhong);

        jBtnTimPhong_TimPhong.setText(resourceMap.getString("jBtnTimPhong_TimPhong.text")); // NOI18N
        jBtnTimPhong_TimPhong.setName("jBtnTimPhong_TimPhong"); // NOI18N
        jPanel4.add(jBtnTimPhong_TimPhong);

        jPaneTimPhong.setLeftComponent(jPanel4);

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(78, 7));
        jLabel1.setMinimumSize(new java.awt.Dimension(78, 7));
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel5.add(jLabel1);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setName("jTable1"); // NOI18N
        jScrollPane1.setViewportView(jTable1);

        jPanel5.add(jScrollPane1);

        jPaneTimPhong.setRightComponent(jPanel5);

        setComponent(jSplitPane1);
        setStatusBar(statusPanel);
    }// </editor-fold>//GEN-END:initComponents

    //click on button Xem phong
    private void jBtnXemPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnXemPhongMouseClicked
        // TODO add your handling code here:
        jRightPanel.add(jPaneXemChiTiet, -1);
        jPaneXemChiTiet.setVisible(true);                

    }//GEN-LAST:event_jBtnXemPhongMouseClicked

    private void jBtnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThongKeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThongKeMouseClicked

    private void jBtnTimPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimPhongMouseClicked
        // TODO add your handling code here:
        jRightPanel.remove(jPaneXemChiTiet);
        jRightPanel.add(jPaneTimPhong,-1);
        jPaneTimPhong.setVisible(true);
    }//GEN-LAST:event_jBtnTimPhongMouseClicked

    private void jBtnThuePhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThuePhongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnThuePhongMouseClicked

    private void jBtnTraPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTraPhongMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnTraPhongMouseClicked

    private void jBtnCauHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCauHinhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCauHinhMouseClicked

    private void jBtnSubmitXMLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSubmitXMLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnSubmitXMLMouseClicked

    private void jBtnThoat_XemChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThoat_XemChiTietMouseClicked
        // TODO add your handling code here:
        jRightPanel.remove(jPaneXemChiTiet);
    }//GEN-LAST:event_jBtnThoat_XemChiTietMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCapNhat_XemChiTiet;
    private javax.swing.JButton jBtnCauHinh;
    private javax.swing.JButton jBtnChinhSua_XemChiTiet;
    private javax.swing.JButton jBtnSubmitXML;
    private javax.swing.JButton jBtnThoat_TimPhong;
    private javax.swing.JButton jBtnThoat_XemChiTiet;
    private javax.swing.JButton jBtnThongKe;
    private javax.swing.JButton jBtnThuePhong;
    private javax.swing.JButton jBtnThuePhong_XemChiTiet;
    private javax.swing.JButton jBtnTimPhong;
    private javax.swing.JButton jBtnTimPhong_TimPhong;
    private javax.swing.JButton jBtnTraPhong;
    private javax.swing.JButton jBtnXemPhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelGiaTien_XemChiTiet;
    private javax.swing.JLabel jLabelHinhPhong_XemChiTiet;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTenKhachSan;
    private javax.swing.JLabel jLabelThoiGian;
    private javax.swing.JPanel jLeftPanel;
    private javax.swing.JSplitPane jPaneTimPhong;
    private javax.swing.JSplitPane jPaneXemChiTiet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JSplitPane jSplitPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel jTopPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel statusAnimationLabel;
    private javax.swing.JLabel statusMessageLabel;
    private javax.swing.JPanel statusPanel;
    // End of variables declaration//GEN-END:variables

    private final Timer messageTimer;
    private final Timer busyIconTimer;
    private final Icon idleIcon;
    private final Icon[] busyIcons = new Icon[15];
    private int busyIconIndex = 0;

    private JDialog aboutBox;
}
