/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogXemChiTiet.java
 *
 * Created on Dec 24, 2009, 12:32:35 AM
 */

package client;

import DTO.Phong;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author bin
 */
public class JDialogXemChiTiet extends javax.swing.JDialog {

    private Phong phong;
    /** Creates new form JDialogXemChiTiet */
    public JDialogXemChiTiet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setDefaultCloseOperation(JDialogXemChiTiet.DISPOSE_ON_CLOSE);
        this.pack();
    }

    JDialogXemChiTiet(java.awt.Frame parent, boolean modal, Phong phong) {
        super(parent, modal);
        initComponents();

        this.setTitle("Xem chi tiet phong");
        this.setDefaultCloseOperation(JDialogXemChiTiet.DISPOSE_ON_CLOSE);

        this.phong = phong;
        this.setSize(500, 500);
        this.pack();

        int cost = phong.getGia() + phong.getIdLoaiPhong().getGia();
        String strLoaiPhong = phong.getIdLoaiPhong().getTen();

        this.jTxtGiaTien.setText("" + cost);
        this.jTxtLau.setText("" + phong.getLau());
        this.jTxtLoaiPhong.setText(strLoaiPhong);
        this.jTxtMoTa.setText(phong.getMoTa());
        this.jTxtSoPhong.setText("" + phong.getId());
        this.jTxtTinhTrang.setText(phong.getIdTinhTrang().getTen());

        //set icon to display
        strLoaiPhong = strLoaiPhong.toLowerCase();
        ClassLoader cldr = this.getClass().getClassLoader();
        java.net.URL imageURL;
        if(strLoaiPhong.contains("vip"))
            imageURL = cldr.getResource("client/resources/PhongVIP.png");
        else if(strLoaiPhong.contains("hang trung"))
            imageURL = cldr.getResource("client/resources/PhongHangTrung.png");
        else if(strLoaiPhong.contains("hang thuong"))
            imageURL = cldr.getResource("client/resources/PhongHangThuong.png");
        else//truong hop khong khop thi gan dai luon :D
            imageURL = cldr.getResource("client/resources/PhongHangTrung.png");
        this.jLabelHinhPhong.setIcon(null);

        ImageIcon icon = new ImageIcon(imageURL);
        if(icon!=null)
            this.jLabelHinhPhong.setIcon(icon);
    }

    public JDialogXemChiTiet(Phong phong) {
        super();
        initComponents();

        this.setDefaultCloseOperation(JDialogXemChiTiet.DISPOSE_ON_CLOSE);
        this.pack();

        this.phong = phong;

        int cost = phong.getGia() + phong.getIdLoaiPhong().getGia();
        String strLoaiPhong = phong.getIdLoaiPhong().getTen();

        this.jTxtGiaTien.setText("" + cost);
        this.jTxtLau.setText("" + phong.getLau());
        this.jTxtLoaiPhong.setText(strLoaiPhong);
        this.jTxtMoTa.setText(phong.getMoTa());
        this.jTxtSoPhong.setText("" + phong.getId());
        this.jTxtTinhTrang.setText(phong.getIdTinhTrang().getTen());

        //set icon to display
        strLoaiPhong = strLoaiPhong.toLowerCase();
        ClassLoader cldr = this.getClass().getClassLoader();
        java.net.URL imageURL;
        if(strLoaiPhong.contains("vip"))
            imageURL = cldr.getResource("client/resources/PhongVIP.png");
        else if(strLoaiPhong.contains("hang trung"))
            imageURL = cldr.getResource("client/resources/PhongHangTrung.png");
        else if(strLoaiPhong.contains("hang thuong"))
            imageURL = cldr.getResource("client/resources/PhongHangThuong.png");
        else//truong hop khong khop thi gan dai luon :D
            imageURL = cldr.getResource("client/resources/PhongHangTrung.png");
        this.jLabelHinhPhong.setIcon(null);

        ImageIcon icon = new ImageIcon(imageURL);
        if(icon!=null)
            this.jLabelHinhPhong.setIcon(icon);
    }

    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelHinhPhong = new javax.swing.JLabel();
        jLabelGiaTien1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtSoPhong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtLau = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtLoaiPhong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtMoTa = new javax.swing.JTextArea();
        jBtnCapNhat = new javax.swing.JButton();
        jBtnChinhSua = new javax.swing.JButton();
        jTxtGiaTien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtTinhTrang = new javax.swing.JTextField();
        bgLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JDialogXemChiTiet.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(179, 80));
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabelHinhPhong.setIcon(resourceMap.getIcon("jLabelHinhPhong.icon")); // NOI18N
        jLabelHinhPhong.setName("jLabelHinhPhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 18);
        jPanel8.add(jLabelHinhPhong, gridBagConstraints);

        jLabelGiaTien1.setText(resourceMap.getString("jLabelGiaTien1.text")); // NOI18N
        jLabelGiaTien1.setName("jLabelGiaTien1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabelGiaTien1, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabel4, gridBagConstraints);

        jTxtSoPhong.setBackground(resourceMap.getColor("jTxtSoPhong.background")); // NOI18N
        jTxtSoPhong.setColumns(10);
        jTxtSoPhong.setEditable(false);
        jTxtSoPhong.setName("jTxtSoPhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtSoPhong, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabel2, gridBagConstraints);

        jTxtLau.setBackground(resourceMap.getColor("jTxtLau.background")); // NOI18N
        jTxtLau.setEditable(false);
        jTxtLau.setName("jTxtLau"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtLau, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabel6, gridBagConstraints);

        jTxtLoaiPhong.setBackground(resourceMap.getColor("jTxtLoaiPhong.background")); // NOI18N
        jTxtLoaiPhong.setEditable(false);
        jTxtLoaiPhong.setName("jTxtLoaiPhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtLoaiPhong, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 85, 10);
        jPanel8.add(jLabel8, gridBagConstraints);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTxtMoTa.setBackground(resourceMap.getColor("jTxtMoTa.background")); // NOI18N
        jTxtMoTa.setColumns(20);
        jTxtMoTa.setEditable(false);
        jTxtMoTa.setRows(3);
        jTxtMoTa.setName("jTxtMoTa"); // NOI18N
        jScrollPane2.setViewportView(jTxtMoTa);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jScrollPane2, gridBagConstraints);

        jBtnCapNhat.setText(resourceMap.getString("jBtnCapNhat.text")); // NOI18N
        jBtnCapNhat.setEnabled(false);
        jBtnCapNhat.setName("jBtnCapNhat"); // NOI18N
        jBtnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        jPanel8.add(jBtnCapNhat, gridBagConstraints);

        jBtnChinhSua.setText(resourceMap.getString("jBtnChinhSua.text")); // NOI18N
        jBtnChinhSua.setName("jBtnChinhSua"); // NOI18N
        jBtnChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.insets = new java.awt.Insets(15, 0, 0, 0);
        jPanel8.add(jBtnChinhSua, gridBagConstraints);

        jTxtGiaTien.setBackground(resourceMap.getColor("jTxtGiaTien.background")); // NOI18N
        jTxtGiaTien.setEditable(false);
        jTxtGiaTien.setText(resourceMap.getString("jTxtGiaTien.text")); // NOI18N
        jTxtGiaTien.setName("jTxtGiaTien"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtGiaTien, gridBagConstraints);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        jPanel8.add(jLabel1, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabel3, gridBagConstraints);

        jTxtTinhTrang.setBackground(resourceMap.getColor("jTxtTinhTrang.background")); // NOI18N
        jTxtTinhTrang.setEditable(false);
        jTxtTinhTrang.setText(resourceMap.getString("jTxtTinhTrang.text")); // NOI18N
        jTxtTinhTrang.setName("jTxtTinhTrang"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtTinhTrang, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(jPanel8, gridBagConstraints);

        bgLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel4.setIcon(resourceMap.getIcon("bgLabel4.icon")); // NOI18N
        bgLabel4.setName("bgLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(bgLabel4, gridBagConstraints);

        getContentPane().add(jPanel7, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCapNhatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMousePressed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this.getComponent(0),"Ban co muon thay doi hay khong?" , "Thong bao", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION)
        {
            Phong p = new Phong();

            //p.setGia()

            JOptionPane.showMessageDialog(this.getComponent(0),"Cap nhat thanh cong" , "Thong bao", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            //restore old value
            int cost = phong.getGia() + phong.getIdLoaiPhong().getGia();
            String strLoaiPhong = phong.getIdLoaiPhong().getTen();

            this.jTxtGiaTien.setText("" + cost);
            this.jTxtLau.setText("" + phong.getLau());
            this.jTxtLoaiPhong.setText(strLoaiPhong);
            this.jTxtMoTa.setText(phong.getMoTa());
            this.jTxtSoPhong.setText("" + phong.getId());
            this.jTxtTinhTrang.setText(phong.getIdTinhTrang().getTen());
        }

        //disable fields
        this.jBtnCapNhat.setEnabled(false);

        this.jTxtGiaTien.setEditable(false);
        this.jTxtLau.setEditable(false);
        this.jTxtLoaiPhong.setEditable(false);
        this.jTxtMoTa.setEditable(false);
        this.jTxtSoPhong.setEditable(false);
        this.jTxtTinhTrang.setEditable(false);
    }//GEN-LAST:event_jBtnCapNhatMousePressed

    private void jBtnChinhSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMousePressed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this.getComponent(0),"Ban co muon sua hay khong?" , "Thong bao", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION)
        {
            //enable fields
            this.jBtnCapNhat.setEnabled(true);

            this.jTxtGiaTien.setEditable(true);
            this.jTxtLau.setEditable(true);
            this.jTxtLoaiPhong.setEditable(true);
            this.jTxtMoTa.setEditable(true);
            this.jTxtSoPhong.setEditable(true);
            this.jTxtTinhTrang.setEditable(true);
        }
    }//GEN-LAST:event_jBtnChinhSuaMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogXemChiTiet dialog = new JDialogXemChiTiet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel4;
    private javax.swing.JButton jBtnCapNhat;
    private javax.swing.JButton jBtnChinhSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelGiaTien1;
    private javax.swing.JLabel jLabelHinhPhong;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtGiaTien;
    private javax.swing.JTextField jTxtLau;
    private javax.swing.JTextField jTxtLoaiPhong;
    private javax.swing.JTextArea jTxtMoTa;
    private javax.swing.JTextField jTxtSoPhong;
    private javax.swing.JTextField jTxtTinhTrang;
    // End of variables declaration//GEN-END:variables

}