/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JMainDialog.java
 *
 * Created on Jan 2, 2010, 5:28:32 PM
 */

package client;

import java.awt.CardLayout;

/**
 *
 * @author bin
 */
public class JMainDialog extends javax.swing.JDialog {

    /** Creates new form JMainDialog */
    public JMainDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        this.setSize(855, 685);
        this.setDefaultCloseOperation(JMainDialog.DISPOSE_ON_CLOSE);
        
        myInit();

        //853 684
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitMainPane = new javax.swing.JSplitPane();
        jTopPanel = new javax.swing.JPanel();
        jLabelTenKhachSan = new javax.swing.JLabel();
        jLabelThoiGian = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jLeftPanel = new javax.swing.JPanel();
        jToggleBtnXemPhong = new javax.swing.JToggleButton();
        jToggleBtnTimPhong = new javax.swing.JToggleButton();
        jToggleBtnThuePhong = new javax.swing.JToggleButton();
        jToggleBtnTraPhong = new javax.swing.JToggleButton();
        jToggleBtnThongKe = new javax.swing.JToggleButton();
        jToggleBtnSubmitXML = new javax.swing.JToggleButton();
        jToggleBtnCauHinh = new javax.swing.JToggleButton();
        jToggleBtnHelp = new javax.swing.JToggleButton();
        jToggleBtnAbout = new javax.swing.JToggleButton();
        jRightPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JMainDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jSplitMainPane.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitMainPane.setDoubleBuffered(true);
        jSplitMainPane.setName("jSplitMainPane"); // NOI18N

        jTopPanel.setName("jTopPanel"); // NOI18N
        jTopPanel.setLayout(new java.awt.GridBagLayout());

        jLabelTenKhachSan.setBackground(resourceMap.getColor("jLabelTenKhachSan.background")); // NOI18N
        jLabelTenKhachSan.setFont(resourceMap.getFont("jLabelTenKhachSan.font")); // NOI18N
        jLabelTenKhachSan.setForeground(resourceMap.getColor("jLabelTenKhachSan.foreground")); // NOI18N
        jLabelTenKhachSan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTenKhachSan.setText(resourceMap.getString("jLabelTenKhachSan.text")); // NOI18N
        jLabelTenKhachSan.setName("jLabelTenKhachSan"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jTopPanel.add(jLabelTenKhachSan, gridBagConstraints);

        jLabelThoiGian.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelThoiGian.setText(resourceMap.getString("jLabelThoiGian.text")); // NOI18N
        jLabelThoiGian.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabelThoiGian.setName("jLabelThoiGian"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        jTopPanel.add(jLabelThoiGian, gridBagConstraints);

        jLabelLogo.setIcon(resourceMap.getIcon("jLabelLogo.icon")); // NOI18N
        jLabelLogo.setText(resourceMap.getString("jLabelLogo.text")); // NOI18N
        jLabelLogo.setName("jLabelLogo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        jTopPanel.add(jLabelLogo, gridBagConstraints);

        jSplitMainPane.setLeftComponent(jTopPanel);

        jSplitPane2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jSplitPane2.setName("jSplitPane2"); // NOI18N

        jLeftPanel.setName("jLeftPanel"); // NOI18N
        jLeftPanel.setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(jToggleBtnXemPhong);
        jToggleBtnXemPhong.setFont(resourceMap.getFont("jToggleBtnXemPhong.font")); // NOI18N
        jToggleBtnXemPhong.setIcon(resourceMap.getIcon("jToggleBtnXemPhong.icon")); // NOI18N
        jToggleBtnXemPhong.setSelected(true);
        jToggleBtnXemPhong.setText(resourceMap.getString("jToggleBtnXemPhong.text")); // NOI18N
        jToggleBtnXemPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnXemPhong.setIconTextGap(0);
        jToggleBtnXemPhong.setMargin(null);
        jToggleBtnXemPhong.setName("jToggleBtnXemPhong"); // NOI18N
        jToggleBtnXemPhong.setPressedIcon(resourceMap.getIcon("jToggleBtnXemPhong.pressedIcon")); // NOI18N
        jToggleBtnXemPhong.setSelectedIcon(resourceMap.getIcon("jToggleBtnXemPhong.selectedIcon")); // NOI18N
        jToggleBtnXemPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnXemPhongMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnXemPhong, gridBagConstraints);

        buttonGroup1.add(jToggleBtnTimPhong);
        jToggleBtnTimPhong.setFont(resourceMap.getFont("jToggleBtnTimPhong.font")); // NOI18N
        jToggleBtnTimPhong.setIcon(resourceMap.getIcon("jToggleBtnTimPhong.icon")); // NOI18N
        jToggleBtnTimPhong.setText(resourceMap.getString("jToggleBtnTimPhong.text")); // NOI18N
        jToggleBtnTimPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnTimPhong.setIconTextGap(0);
        jToggleBtnTimPhong.setMargin(null);
        jToggleBtnTimPhong.setName("jToggleBtnTimPhong"); // NOI18N
        jToggleBtnTimPhong.setPressedIcon(resourceMap.getIcon("jToggleBtnTimPhong.pressedIcon")); // NOI18N
        jToggleBtnTimPhong.setSelectedIcon(resourceMap.getIcon("jToggleBtnTimPhong.selectedIcon")); // NOI18N
        jToggleBtnTimPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnTimPhongMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnTimPhong, gridBagConstraints);

        buttonGroup1.add(jToggleBtnThuePhong);
        jToggleBtnThuePhong.setFont(resourceMap.getFont("jToggleBtnThuePhong.font")); // NOI18N
        jToggleBtnThuePhong.setIcon(resourceMap.getIcon("jToggleBtnThuePhong.icon")); // NOI18N
        jToggleBtnThuePhong.setText(resourceMap.getString("jToggleBtnThuePhong.text")); // NOI18N
        jToggleBtnThuePhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnThuePhong.setIconTextGap(0);
        jToggleBtnThuePhong.setMargin(null);
        jToggleBtnThuePhong.setName("jToggleBtnThuePhong"); // NOI18N
        jToggleBtnThuePhong.setPressedIcon(resourceMap.getIcon("jToggleBtnThuePhong.pressedIcon")); // NOI18N
        jToggleBtnThuePhong.setSelectedIcon(resourceMap.getIcon("jToggleBtnThuePhong.selectedIcon")); // NOI18N
        jToggleBtnThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnThuePhongMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnThuePhong, gridBagConstraints);

        buttonGroup1.add(jToggleBtnTraPhong);
        jToggleBtnTraPhong.setFont(resourceMap.getFont("jToggleBtnTraPhong.font")); // NOI18N
        jToggleBtnTraPhong.setIcon(resourceMap.getIcon("jToggleBtnTraPhong.icon")); // NOI18N
        jToggleBtnTraPhong.setText(resourceMap.getString("jToggleBtnTraPhong.text")); // NOI18N
        jToggleBtnTraPhong.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnTraPhong.setIconTextGap(0);
        jToggleBtnTraPhong.setMargin(null);
        jToggleBtnTraPhong.setName("jToggleBtnTraPhong"); // NOI18N
        jToggleBtnTraPhong.setPressedIcon(resourceMap.getIcon("jToggleBtnTraPhong.pressedIcon")); // NOI18N
        jToggleBtnTraPhong.setSelectedIcon(resourceMap.getIcon("jToggleBtnTraPhong.selectedIcon")); // NOI18N
        jToggleBtnTraPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnTraPhongMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnTraPhong, gridBagConstraints);

        buttonGroup1.add(jToggleBtnThongKe);
        jToggleBtnThongKe.setFont(resourceMap.getFont("jToggleBtnThongKe.font")); // NOI18N
        jToggleBtnThongKe.setIcon(resourceMap.getIcon("jToggleBtnThongKe.icon")); // NOI18N
        jToggleBtnThongKe.setText(resourceMap.getString("jToggleBtnThongKe.text")); // NOI18N
        jToggleBtnThongKe.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnThongKe.setIconTextGap(0);
        jToggleBtnThongKe.setMargin(null);
        jToggleBtnThongKe.setName("jToggleBtnThongKe"); // NOI18N
        jToggleBtnThongKe.setPressedIcon(resourceMap.getIcon("jToggleBtnThongKe.pressedIcon")); // NOI18N
        jToggleBtnThongKe.setSelectedIcon(resourceMap.getIcon("jToggleBtnThongKe.selectedIcon")); // NOI18N
        jToggleBtnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnThongKeMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnThongKe, gridBagConstraints);

        buttonGroup1.add(jToggleBtnSubmitXML);
        jToggleBtnSubmitXML.setFont(resourceMap.getFont("jToggleBtnSubmitXML.font")); // NOI18N
        jToggleBtnSubmitXML.setIcon(resourceMap.getIcon("jToggleBtnSubmitXML.icon")); // NOI18N
        jToggleBtnSubmitXML.setText(resourceMap.getString("jToggleBtnSubmitXML.text")); // NOI18N
        jToggleBtnSubmitXML.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnSubmitXML.setIconTextGap(0);
        jToggleBtnSubmitXML.setMargin(null);
        jToggleBtnSubmitXML.setName("jToggleBtnSubmitXML"); // NOI18N
        jToggleBtnSubmitXML.setPressedIcon(resourceMap.getIcon("jToggleBtnSubmitXML.pressedIcon")); // NOI18N
        jToggleBtnSubmitXML.setSelectedIcon(resourceMap.getIcon("jToggleBtnSubmitXML.selectedIcon")); // NOI18N
        jToggleBtnSubmitXML.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnSubmitXMLMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnSubmitXML, gridBagConstraints);

        buttonGroup1.add(jToggleBtnCauHinh);
        jToggleBtnCauHinh.setFont(resourceMap.getFont("jToggleBtnCauHinh.font")); // NOI18N
        jToggleBtnCauHinh.setIcon(resourceMap.getIcon("jToggleBtnCauHinh.icon")); // NOI18N
        jToggleBtnCauHinh.setText(resourceMap.getString("jToggleBtnCauHinh.text")); // NOI18N
        jToggleBtnCauHinh.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnCauHinh.setIconTextGap(0);
        jToggleBtnCauHinh.setMargin(null);
        jToggleBtnCauHinh.setName("jToggleBtnCauHinh"); // NOI18N
        jToggleBtnCauHinh.setPressedIcon(resourceMap.getIcon("jToggleBtnCauHinh.pressedIcon")); // NOI18N
        jToggleBtnCauHinh.setSelectedIcon(resourceMap.getIcon("jToggleBtnCauHinh.selectedIcon")); // NOI18N
        jToggleBtnCauHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnCauHinhMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnCauHinh, gridBagConstraints);

        buttonGroup1.add(jToggleBtnHelp);
        jToggleBtnHelp.setFont(resourceMap.getFont("jToggleBtnHelp.font")); // NOI18N
        jToggleBtnHelp.setIcon(resourceMap.getIcon("jToggleBtnHelp.icon")); // NOI18N
        jToggleBtnHelp.setText(resourceMap.getString("jToggleBtnHelp.text")); // NOI18N
        jToggleBtnHelp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnHelp.setIconTextGap(0);
        jToggleBtnHelp.setMargin(null);
        jToggleBtnHelp.setName("jToggleBtnHelp"); // NOI18N
        jToggleBtnHelp.setPressedIcon(resourceMap.getIcon("jToggleBtnHelp.pressedIcon")); // NOI18N
        jToggleBtnHelp.setSelectedIcon(resourceMap.getIcon("jToggleBtnHelp.selectedIcon")); // NOI18N
        jToggleBtnHelp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnHelpMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnHelp, gridBagConstraints);

        buttonGroup1.add(jToggleBtnAbout);
        jToggleBtnAbout.setFont(resourceMap.getFont("jToggleBtnAbout.font")); // NOI18N
        jToggleBtnAbout.setIcon(resourceMap.getIcon("jToggleBtnAbout.icon")); // NOI18N
        jToggleBtnAbout.setText(resourceMap.getString("jToggleBtnAbout.text")); // NOI18N
        jToggleBtnAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleBtnAbout.setIconTextGap(0);
        jToggleBtnAbout.setMargin(null);
        jToggleBtnAbout.setName("jToggleBtnAbout"); // NOI18N
        jToggleBtnAbout.setPressedIcon(resourceMap.getIcon("jToggleBtnAbout.pressedIcon")); // NOI18N
        jToggleBtnAbout.setSelectedIcon(resourceMap.getIcon("jToggleBtnAbout.selectedIcon")); // NOI18N
        jToggleBtnAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jToggleBtnAboutMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 5;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(2, 2, 2, 2);
        jLeftPanel.add(jToggleBtnAbout, gridBagConstraints);

        jSplitPane2.setLeftComponent(jLeftPanel);

        jRightPanel.setName("jRightPanel"); // NOI18N
        jRightPanel.setLayout(new java.awt.CardLayout());
        jSplitPane2.setRightComponent(jRightPanel);

        jSplitMainPane.setBottomComponent(jSplitPane2);

        getContentPane().add(jSplitMainPane, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleBtnXemPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnXemPhongMousePressed
        // TODO add your handling code here:
        //CardLayout cl = (CardLayout)jRightPanel.getLayout();
/*
        int count = jRightPanel.getComponentCount();
        if(count>0)
        {
            jRightPanel.remove(count -1);

            JPanelXemPhong xemPhongPanel = new JPanelXemPhong();
            xemPhongPanel.setName("JPanelXemPhong");
            jRightPanel.add(xemPhongPanel,xemPhongPanel.getName());
        }
 */
        CardLayout cl = (CardLayout)jRightPanel.getLayout();
        cl.show(jRightPanel, panelXemPhong.getName());
}//GEN-LAST:event_jToggleBtnXemPhongMousePressed

    private void jToggleBtnTimPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnTimPhongMousePressed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jRightPanel.getLayout();
        cl.show(jRightPanel, panelTimPhong.getName());
}//GEN-LAST:event_jToggleBtnTimPhongMousePressed

    private void jToggleBtnThuePhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnThuePhongMousePressed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jRightPanel.getLayout();
        cl.show(jRightPanel, panelThuePhong.getName());
}//GEN-LAST:event_jToggleBtnThuePhongMousePressed

    private void jToggleBtnTraPhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnTraPhongMousePressed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jRightPanel.getLayout();
        cl.show(jRightPanel, panelTraPhong.getName());
}//GEN-LAST:event_jToggleBtnTraPhongMousePressed

    private void jToggleBtnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnThongKeMousePressed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jRightPanel.getLayout();
        cl.show(jRightPanel, panelThongKe.getName());
}//GEN-LAST:event_jToggleBtnThongKeMousePressed

    private void jToggleBtnSubmitXMLMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnSubmitXMLMousePressed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jRightPanel.getLayout();
        cl.show(jRightPanel, panelSubmitXML.getName());
}//GEN-LAST:event_jToggleBtnSubmitXMLMousePressed

    private void jToggleBtnCauHinhMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnCauHinhMousePressed
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)jRightPanel.getLayout();
        cl.show(jRightPanel, panelCauhinh.getName());
}//GEN-LAST:event_jToggleBtnCauHinhMousePressed

    private void jToggleBtnHelpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnHelpMousePressed
        // TODO add your handling code here:
}//GEN-LAST:event_jToggleBtnHelpMousePressed

    private void jToggleBtnAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleBtnAboutMousePressed
        // TODO add your handling code here:
        //        if (aboutBox == null) {
        //            JFrame mainFrame = ClientApp.getApplication().getMainFrame();
        //            aboutBox = new ClientAboutBox(mainFrame);
        //            aboutBox.setLocationRelativeTo(mainFrame);
        //        }
        //        ClientApp.getApplication().show(aboutBox);
}//GEN-LAST:event_jToggleBtnAboutMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JMainDialog dialog = new JMainDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelTenKhachSan;
    private javax.swing.JLabel jLabelThoiGian;
    private javax.swing.JPanel jLeftPanel;
    private javax.swing.JPanel jRightPanel;
    private javax.swing.JSplitPane jSplitMainPane;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JToggleButton jToggleBtnAbout;
    private javax.swing.JToggleButton jToggleBtnCauHinh;
    private javax.swing.JToggleButton jToggleBtnHelp;
    private javax.swing.JToggleButton jToggleBtnSubmitXML;
    private javax.swing.JToggleButton jToggleBtnThongKe;
    private javax.swing.JToggleButton jToggleBtnThuePhong;
    private javax.swing.JToggleButton jToggleBtnTimPhong;
    private javax.swing.JToggleButton jToggleBtnTraPhong;
    private javax.swing.JToggleButton jToggleBtnXemPhong;
    private javax.swing.JPanel jTopPanel;
    // End of variables declaration//GEN-END:variables

    //panels
    private JPanelCauHinh panelCauhinh;
    private JPanelSubmitXML panelSubmitXML;
    private JPanelThongKe panelThongKe;
    private JPanelThuePhong panelThuePhong;
    private JPanelTimPhong panelTimPhong;
    private JPanelTraPhong panelTraPhong;
    private JPanelXemPhong panelXemPhong;

    private void myInit() {
        //init panels
        panelCauhinh = new JPanelCauHinh();
        panelCauhinh.setName("panelCauhinh");

        panelSubmitXML = new JPanelSubmitXML();
        panelSubmitXML.setName("panelSubmitXML");

        panelThongKe = new JPanelThongKe();
        panelThongKe.setName("panelThongKe");

        panelThuePhong = new JPanelThuePhong();
        panelThuePhong.setName("panelThuePhong");

        panelTimPhong = new JPanelTimPhong();
        panelTimPhong.setName("panelTimPhong");

        panelTraPhong = new JPanelTraPhong();
        panelTraPhong.setName("panelTraPhong");

        panelXemPhong = new JPanelXemPhong();
        panelXemPhong.setName("panelXemPhong");

        //load and paint default panel
        jRightPanel.add(panelXemPhong,panelXemPhong.getName());
        jRightPanel.add(panelThuePhong,panelThuePhong.getName());
        jRightPanel.add(panelCauhinh,panelCauhinh.getName());
        jRightPanel.add(panelSubmitXML,panelSubmitXML.getName());
        jRightPanel.add(panelThongKe,panelThongKe.getName());
        jRightPanel.add(panelTimPhong,panelTimPhong.getName());
        jRightPanel.add(panelTraPhong,panelTraPhong.getName());
    }
}
