/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelFloor.java
 *
 * Created on Dec 23, 2009, 11:10:24 PM
 */

package client;

import java.awt.GridBagConstraints;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author bin
 */
public class JPanelFloor extends javax.swing.JPanel {

    /** Creates new form JPanelFloor */
    public JPanelFloor() {
        initComponents();

        jPanelViewFloor.removeAll();

        ArrayList arr = new ArrayList();
        arr.add(1);
        arr.add(2);
        arr.add(3);
        arr.add(4);
        arr.add(5);

        int i;
        int n = arr.size();
        int t = 0;
        int d = 0;

        for(i=0;i<n;i++)
        {
            JButton tmp = new JButton("" + i);
            tmp.setName("" + i);
            tmp.setText("Button " + i);

            GridBagConstraints c = new GridBagConstraints();

            c.fill = GridBagConstraints.BOTH;
            c.insets = new java.awt.Insets(9, 9, 9, 9);

            tmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnPress(evt);
            }
            });

            if(i%2==0)
            {
                //phong chan o duoi
                c.gridx = d;
                c.gridy = 1;
                d++;
            }
            else
            {
                //phong le ben tren
                c.gridx = t;
                c.gridy = 0;
                t++;
            }

            jPanelViewFloor.add(tmp, c);
        }
    }

    private void jBtnPress(MouseEvent evt) {

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelViewFloor = new javax.swing.JPanel();
        bgLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridBagLayout());

        jPanelViewFloor.setName("jPanelViewFloor"); // NOI18N
        jPanelViewFloor.setOpaque(false);
        jPanelViewFloor.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jPanelViewFloor, gridBagConstraints);

        bgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelFloor.class);
        bgLabel.setIcon(resourceMap.getIcon("bgLabel.icon")); // NOI18N
        bgLabel.setText(resourceMap.getString("bgLabel.text")); // NOI18N
        bgLabel.setName("bgLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(bgLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * repaint the floor
     */
    public void repaintFloor(int numFloor)
    {
        //remove old buttons and labels
        jPanelViewFloor.removeAll();
        
        
        //add new buttons and labels
        ArrayList arr = new ArrayList();
        int i;

        for(i=0;i<numFloor*2;i++)
            arr.add(i);


        int n = arr.size();
        int t = 0;
        int d = 0;

        for(i=0;i<n;i++)
        {
            JButton tmp = new JButton("" + i);
            tmp.setName("" + i);
            tmp.setText("Button " + i);

            GridBagConstraints c = new GridBagConstraints();

            c.fill = GridBagConstraints.BOTH;
            c.insets = new java.awt.Insets(9, 9, 9, 9);

            tmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnPress(evt);
            }
            });

            if(i%2==0)
            {
                //phong chan o duoi
                c.gridx = d;
                c.gridy = 1;
                d++;
            }
            else
            {
                //phong le ben tren
                c.gridx = t;
                c.gridy = 0;
                t++;
            }

            jPanelViewFloor.add(tmp, c);
        }

        jPanelViewFloor.validate();
     this.repaint();
    }

    private JDialogXemChiTiet xemChiTietDlg;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JPanel jPanelViewFloor;
    // End of variables declaration//GEN-END:variables

}
