/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelCauHinh.java
 *
 * Created on Dec 18, 2009, 12:40:06 PM
 */

package client;

import BUS.KhachHangController;
import BUS.KhachSanController;
import BUS.PhongController;
import BUS.ThamSoController;
import DTO.KhachHang;
import DTO.KhachSan;
import DTO.Phong;
import DTO.PhongHangThuong;
import DTO.PhongHangTrung;
import DTO.PhongVIP;
import DTO.ThamSo;
import Utils.MyCompare;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;


/**
 *
 * @author huy
 */
public class JPanelCauHinh extends javax.swing.JPanel {

    /** Creates new form JPanelCauHinh */
    public JPanelCauHinh() {
        initComponents();

        phongController = new PhongController();
        khachController = new KhachHangController();
        thamSoController = new ThamSoController();
        khachSanController = new KhachSanController();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelHeThong = new javax.swing.JPanel();
        jMainPanelHeThong = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jtxtTen = new javax.swing.JTextField();
        jTxtDiaChi = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtWebsite = new javax.swing.JTextField();
        jFtxtDienThoai = new javax.swing.JFormattedTextField();
        jFtxtFax = new javax.swing.JFormattedTextField();
        jBtnLuu = new javax.swing.JButton();
        jBtnSua = new javax.swing.JButton();
        bgLabel1 = new javax.swing.JLabel();
        jPanelNghiepVu = new javax.swing.JPanel();
        jMainPanelNghiepVu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jCbLoaiPhong = new javax.swing.JComboBox();
        jCbLoaiKhach = new javax.swing.JComboBox();
        jBtnChinhSua = new javax.swing.JButton();
        jBtnCapNhat = new javax.swing.JButton();
        imgConfig = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtGiaPhong = new javax.swing.JFormattedTextField();
        jTxtGiaKhach = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jcbThamSo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jTxtGiaTriThamSo = new javax.swing.JFormattedTextField();
        jCheckThamSo = new javax.swing.JCheckBox();
        bgLabel2 = new javax.swing.JLabel();
        bgLabel = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setDoubleBuffered(true);
        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        jPanelHeThong.setName("jPanelTabHeThong"); // NOI18N
        jPanelHeThong.setLayout(new java.awt.GridBagLayout());

        jMainPanelHeThong.setName("jMainPanelHeThong"); // NOI18N
        jMainPanelHeThong.setOpaque(false);
        jMainPanelHeThong.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelCauHinh.class);
        jLabel16.setFont(resourceMap.getFont("jLabel16.font")); // NOI18N
        jLabel16.setForeground(resourceMap.getColor("jLabel16.foreground")); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 20, 5);
        jMainPanelHeThong.add(jLabel16, gridBagConstraints);

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jMainPanelHeThong.add(jLabel9, gridBagConstraints);

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jMainPanelHeThong.add(jLabel10, gridBagConstraints);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jMainPanelHeThong.add(jLabel11, gridBagConstraints);

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jMainPanelHeThong.add(jLabel12, gridBagConstraints);

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jMainPanelHeThong.add(jLabel13, gridBagConstraints);

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jMainPanelHeThong.add(jLabel14, gridBagConstraints);

        jtxtTen.setBackground(resourceMap.getColor("jTxtWebsite.background")); // NOI18N
        jtxtTen.setEditable(false);
        jtxtTen.setText(resourceMap.getString("jtxtTen.text")); // NOI18N
        jtxtTen.setName("jtxtTen"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        jMainPanelHeThong.add(jtxtTen, gridBagConstraints);

        jTxtDiaChi.setBackground(resourceMap.getColor("jTxtWebsite.background")); // NOI18N
        jTxtDiaChi.setEditable(false);
        jTxtDiaChi.setText(resourceMap.getString("jTxtDiaChi.text")); // NOI18N
        jTxtDiaChi.setName("jTxtDiaChi"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        jMainPanelHeThong.add(jTxtDiaChi, gridBagConstraints);

        jTxtEmail.setBackground(resourceMap.getColor("jTxtWebsite.background")); // NOI18N
        jTxtEmail.setEditable(false);
        jTxtEmail.setText(resourceMap.getString("jTxtEmail.text")); // NOI18N
        jTxtEmail.setName("jTxtEmail"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        jMainPanelHeThong.add(jTxtEmail, gridBagConstraints);

        jTxtWebsite.setBackground(resourceMap.getColor("jTxtWebsite.background")); // NOI18N
        jTxtWebsite.setEditable(false);
        jTxtWebsite.setText(resourceMap.getString("jTxtWebsite.text")); // NOI18N
        jTxtWebsite.setName("jTxtWebsite"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        jMainPanelHeThong.add(jTxtWebsite, gridBagConstraints);

        jFtxtDienThoai.setBackground(resourceMap.getColor("jFtxtDienThoai.background")); // NOI18N
        jFtxtDienThoai.setEditable(false);
        jFtxtDienThoai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFtxtDienThoai.setText(resourceMap.getString("jFtxtDienThoai.text")); // NOI18N
        jFtxtDienThoai.setName("jFtxtDienThoai"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        jMainPanelHeThong.add(jFtxtDienThoai, gridBagConstraints);

        jFtxtFax.setBackground(resourceMap.getColor("jTxtWebsite.background")); // NOI18N
        jFtxtFax.setEditable(false);
        jFtxtFax.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFtxtFax.setText(resourceMap.getString("jFtxtFax.text")); // NOI18N
        jFtxtFax.setName("jFtxtFax"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 15, 5, 5);
        jMainPanelHeThong.add(jFtxtFax, gridBagConstraints);

        jBtnLuu.setBackground(resourceMap.getColor("jBtnLuu.background")); // NOI18N
        jBtnLuu.setText(resourceMap.getString("jBtnLuu.text")); // NOI18N
        jBtnLuu.setEnabled(false);
        jBtnLuu.setName("jBtnLuu"); // NOI18N
        jBtnLuu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnLuuMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 30, 5, 0);
        jMainPanelHeThong.add(jBtnLuu, gridBagConstraints);

        jBtnSua.setBackground(resourceMap.getColor("jBtnLuu.background")); // NOI18N
        jBtnSua.setText(resourceMap.getString("jBtnSua.text")); // NOI18N
        jBtnSua.setName("jBtnSua"); // NOI18N
        jBtnSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jBtnSuaMouseReleased(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 60, 5, 60);
        jMainPanelHeThong.add(jBtnSua, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelHeThong.add(jMainPanelHeThong, gridBagConstraints);

        bgLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel1.setIcon(resourceMap.getIcon("bgLabel1.icon")); // NOI18N
        bgLabel1.setText(resourceMap.getString("bgLabel1.text")); // NOI18N
        bgLabel1.setName("bgLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelHeThong.add(bgLabel1, gridBagConstraints);

        jTabbedPane1.addTab(resourceMap.getString("jPanelTabHeThong.TabConstraints.tabTitle"), resourceMap.getIcon("jPanelTabHeThong.TabConstraints.tabIcon"), jPanelHeThong); // NOI18N

        jPanelNghiepVu.setName("jPanelTabNghiepVu"); // NOI18N
        jPanelNghiepVu.setLayout(new java.awt.GridBagLayout());

        jMainPanelNghiepVu.setName("jMainPanelNghiepVu"); // NOI18N
        jMainPanelNghiepVu.setOpaque(false);
        jMainPanelNghiepVu.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 0);
        jMainPanelNghiepVu.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel2.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jLabel2, gridBagConstraints);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jLabel3, gridBagConstraints);

        jCbLoaiPhong.setBackground(resourceMap.getColor("jCbLoaiKhach.background")); // NOI18N
        jCbLoaiPhong.setName("jCbLoaiPhong"); // NOI18N
        jCbLoaiPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbLoaiPhongItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jCbLoaiPhong, gridBagConstraints);

        jCbLoaiKhach.setBackground(resourceMap.getColor("jCbLoaiKhach.background")); // NOI18N
        jCbLoaiKhach.setName("jCbLoaiKhach"); // NOI18N
        jCbLoaiKhach.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbLoaiKhachItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jCbLoaiKhach, gridBagConstraints);

        jBtnChinhSua.setBackground(resourceMap.getColor("jBtnChinhSua.background")); // NOI18N
        jBtnChinhSua.setText(resourceMap.getString("jBtnChinhSua.text")); // NOI18N
        jBtnChinhSua.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnChinhSua.setName("jBtnChinhSua"); // NOI18N
        jBtnChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(21, 13, 10, 13);
        jMainPanelNghiepVu.add(jBtnChinhSua, gridBagConstraints);

        jBtnCapNhat.setBackground(resourceMap.getColor("jBtnChinhSua.background")); // NOI18N
        jBtnCapNhat.setText(resourceMap.getString("jBtnCapNhat.text")); // NOI18N
        jBtnCapNhat.setEnabled(false);
        jBtnCapNhat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnCapNhat.setName("jBtnCapNhat"); // NOI18N
        jBtnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(21, 10, 10, 10);
        jMainPanelNghiepVu.add(jBtnCapNhat, gridBagConstraints);

        imgConfig.setIcon(resourceMap.getIcon("imgConfig.icon")); // NOI18N
        imgConfig.setText(resourceMap.getString("imgConfig.text")); // NOI18N
        imgConfig.setName("imgConfig"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 0, 31);
        jMainPanelNghiepVu.add(imgConfig, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        jMainPanelNghiepVu.add(jLabel4, gridBagConstraints);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 0);
        jMainPanelNghiepVu.add(jLabel5, gridBagConstraints);

        jTxtGiaPhong.setBackground(resourceMap.getColor("jTxtGiaPhong.background")); // NOI18N
        jTxtGiaPhong.setColumns(10);
        jTxtGiaPhong.setEditable(false);
        jTxtGiaPhong.setText(resourceMap.getString("jTxtGiaPhong.text")); // NOI18N
        jTxtGiaPhong.setName("jTxtGiaPhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jTxtGiaPhong, gridBagConstraints);

        jTxtGiaKhach.setBackground(resourceMap.getColor("jTxtGiaPhong.background")); // NOI18N
        jTxtGiaKhach.setColumns(10);
        jTxtGiaKhach.setEditable(false);
        jTxtGiaKhach.setText(resourceMap.getString("jTxtGiaKhach.text")); // NOI18N
        jTxtGiaKhach.setName("jTxtGiaKhach"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jTxtGiaKhach, gridBagConstraints);

        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jLabel6, gridBagConstraints);

        jcbThamSo.setBackground(resourceMap.getColor("jcbThamSo.background")); // NOI18N
        jcbThamSo.setName("jcbThamSo"); // NOI18N
        jcbThamSo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbThamSoItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jcbThamSo, gridBagConstraints);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 50, 10, 10);
        jMainPanelNghiepVu.add(jLabel7, gridBagConstraints);

        jTxtGiaTriThamSo.setBackground(resourceMap.getColor("jTxtGiaTriThamSo.background")); // NOI18N
        jTxtGiaTriThamSo.setEditable(false);
        jTxtGiaTriThamSo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jTxtGiaTriThamSo.setName("jTxtGiaTriThamSo"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jTxtGiaTriThamSo, gridBagConstraints);

        jCheckThamSo.setText(resourceMap.getString("jCheckThamSo.text")); // NOI18N
        jCheckThamSo.setEnabled(false);
        jCheckThamSo.setName("jCheckThamSo"); // NOI18N
        jCheckThamSo.setOpaque(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jMainPanelNghiepVu.add(jCheckThamSo, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelNghiepVu.add(jMainPanelNghiepVu, gridBagConstraints);

        bgLabel2.setIcon(resourceMap.getIcon("bgLabel2.icon")); // NOI18N
        bgLabel2.setText(resourceMap.getString("bgLabel2.text")); // NOI18N
        bgLabel2.setName("bgLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanelNghiepVu.add(bgLabel2, gridBagConstraints);

        jTabbedPane1.addTab(resourceMap.getString("jPanelTabNghiepVu.TabConstraints.tabTitle"), resourceMap.getIcon("jPanelTabNghiepVu.TabConstraints.tabIcon"), jPanelNghiepVu); // NOI18N

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(jTabbedPane1, gridBagConstraints);

        bgLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel.setIcon(resourceMap.getIcon("bgLabel.icon")); // NOI18N
        bgLabel.setText(resourceMap.getString("bgLabel.text")); // NOI18N
        bgLabel.setName("bgLabel"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        add(bgLabel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnChinhSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMousePressed
        // TODO add your handling code here:
        if(!this.jBtnChinhSua.isEnabled())
            return;

        int result = JOptionPane.showConfirmDialog(this.getComponent(0),"Bạn có muốn sửa hay không?" , "Thông Báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION)
        {
            //set editable
            this.jBtnCapNhat.setEnabled(true);
            this.jTxtGiaKhach.setEditable(true);
            this.jTxtGiaPhong.setEditable(true);
            this.jTxtGiaTriThamSo.setEditable(true);
            this.jCheckThamSo.setEnabled(true);

            this.jBtnChinhSua.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnChinhSuaMousePressed

    private void jBtnCapNhatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMousePressed
        // TODO add your handling code here:
        if(!this.jBtnCapNhat.isEnabled())
            return;

        int result = JOptionPane.showConfirmDialog(this.getComponent(0),"Bạn có muốn lưu những thay đổi không?" , "Thông Báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION)
        {
            String s = jTxtGiaKhach.getText();
            if(s.equals(""))
            {
                JOptionPane.showMessageDialog(this.getComponent(0), "Nhập vào đơn giá khách hàng!","Thông Báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int giaKhach = Integer.parseInt(s);

            s = jTxtGiaPhong.getText();
            if(s.equals(""))
            {
                JOptionPane.showMessageDialog(this.getComponent(0), "Nhập vào đơn giá phòng!","Thông Báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            int giaPhong = Integer.parseInt(s);

            s = jTxtGiaTriThamSo.getText();
            if(s.equals(""))
            {
                JOptionPane.showMessageDialog(this.getComponent(0), "Nhập vào giá trị tham số!","Thông Báo", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int giaTriThamSo = Integer.parseInt(s);

            KhachHang loaiKhachHang = layLoaiKhachHangTheoTen(jCbLoaiKhach.getSelectedItem().toString());
            loaiKhachHang.setDonGiaKhachHang(giaKhach);
            
            Phong loaiPhong = layGiaLoaiPhongTheoTen(jCbLoaiPhong.getSelectedItem().toString());
            //loaiPhong.setGia(giaPhong);
            
            ThamSo thamSo = layThamSoTheoTen(jcbThamSo.getSelectedItem().toString());
            thamSo.setValue(giaTriThamSo);
            thamSo.setUse(jCheckThamSo.isSelected());

            if(!phongController.capNhatLoaiPhong(loaiPhong.getTenLoaiPhong(),giaPhong))
            {
                JOptionPane.showMessageDialog(this.getComponent(0),"Cập nhật gía tiền phòng thất bại" , "Thông Báo", JOptionPane.ERROR_MESSAGE);
            }else            
            if(!khachController.capNhatLoaiKhachHang(loaiKhachHang.getTenLoaiKhachHang(),loaiKhachHang.getDonGiaKhachHang()))
            {
                JOptionPane.showMessageDialog(this.getComponent(0),"Cập nhật gía tiền khách hàng thất bại" , "Thông Báo", JOptionPane.ERROR_MESSAGE);
            }else
                if(!thamSoController.capNhatThamSo(thamSo))
                {
                    JOptionPane.showMessageDialog(this.getComponent(0),"Cập nhật tham số" + thamSo.getName() + "thất bại" , "Thông Báo", JOptionPane.ERROR_MESSAGE);
                }
                else
                JOptionPane.showMessageDialog(this.getComponent(0),"Cập nhật thành công" , "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
        }
        else
        {
            //restore old values
            initComboLoaiKhachHang();
            initComboLoaiPhong();
            initComboThamSo();
        }
        
        //disable fields
        this.jBtnCapNhat.setEnabled(false);
        this.jTxtGiaKhach.setEditable(false);
        this.jTxtGiaPhong.setEditable(false);
        this.jTxtGiaTriThamSo.setEditable(false);
        this.jCheckThamSo.setEnabled(false);

        this.jBtnChinhSua.setEnabled(true);
    }//GEN-LAST:event_jBtnCapNhatMousePressed

    private void jCbLoaiPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbLoaiPhongItemStateChanged
        // TODO add your handling code here:
        if(jCbLoaiPhong.getItemCount()>0)
        {
            Phong phong = layGiaLoaiPhongTheoTen(jCbLoaiPhong.getSelectedItem().toString());
            jTxtGiaPhong.setText("" + phong.getDonGiaPhong());
        }
    }//GEN-LAST:event_jCbLoaiPhongItemStateChanged

    private void jCbLoaiKhachItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbLoaiKhachItemStateChanged
        // TODO add your handling code here:
        if(jCbLoaiKhach.getItemCount()>0)
        {
            KhachHang loaiKhach = layLoaiKhachHangTheoTen(jCbLoaiKhach.getSelectedItem().toString());
            jTxtGiaKhach.setText("" + loaiKhach.getDonGiaKhachHang());
        }
    }//GEN-LAST:event_jCbLoaiKhachItemStateChanged

    private SwingWorker<ArrayList<String>,Void> workerGetDSLoaiPhong = new SwingWorker<ArrayList<String>,Void>() {

        private PhongController phongController;

        @Override
        protected ArrayList<String> doInBackground() throws Exception {
            phongController = new PhongController();
            return phongController.getDSLoaiPhong();
        }
    };

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        WorkerGetListLoaiKhachHang workerGetLoaiKhach = new WorkerGetListLoaiKhachHang();
        workerGetLoaiKhach.run();
        
        workerGetDSLoaiPhong.run();

        WorkerGetListThamSo workerGetThamSo = new WorkerGetListThamSo();
        workerGetThamSo.run();


        khachSan = khachSanController.layKhachSan();
        if(khachSan!=null)
        {
            hienThiThongTinKhachSan(khachSan);
        }

        try {
            lstLoaiKhachHang = workerGetLoaiKhach.get();
        } catch (InterruptedException ex) {
            Logger.getLogger(JPanelCauHinh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExecutionException ex) {
            Logger.getLogger(JPanelCauHinh.class.getName()).log(Level.SEVERE, null, ex);
        }

        ArrayList<String> lstLoaiPhong = null;
        try {
            lstLoaiPhong = workerGetDSLoaiPhong.get();
        } catch (InterruptedException ex) {
            Logger.getLogger(JPanelCauHinh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExecutionException ex) {
            Logger.getLogger(JPanelCauHinh.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            lstThamSo = workerGetThamSo.get();
        } catch (InterruptedException ex) {
            Logger.getLogger(JPanelCauHinh.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExecutionException ex) {
            Logger.getLogger(JPanelCauHinh.class.getName()).log(Level.SEVERE, null, ex);
        }

        if(lstLoaiKhachHang!=null)
        {
            initComboLoaiKhachHang();
        }

        if(lstLoaiPhong!=null)
        {
            this.lstGiaLoaiPhong = new ArrayList<Phong>();
            int i;
            for(i=0;i<lstLoaiPhong.size();i++)
            {
                Phong phong = null;
                String tenLoaiPhong = lstLoaiPhong.get(i);//.toLowerCase();
                if(MyCompare.compareString(tenLoaiPhong, "VIP") == 0)
                //if(tenLoaiPhong.equals("vip"))
                {
                    phong = new PhongVIP();
                }
                else
                {
                    if(MyCompare.compareString(tenLoaiPhong, "Hạng Trung") == 0)
                    //if(tenLoaiPhong.equals("hang trung"))
                    {
                        phong = new PhongHangTrung();
                    }
                    else
                        phong = new PhongHangThuong();
                }
                phong.setDonGiaPhong(phongController.getDonGiaPhongTheoTen(phong.getTenLoaiPhong()));
                this.lstGiaLoaiPhong.add(phong);
            }
            initComboLoaiPhong();            
        }

        if(lstThamSo!=null)
        {
            initComboThamSo();
        }
    }//GEN-LAST:event_formComponentShown

    private void jcbThamSoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbThamSoItemStateChanged
        // TODO add your handling code here:
        if(jcbThamSo.getItemCount()>0)
        {
            ThamSo thamSo = layThamSoTheoTen(jcbThamSo.getSelectedItem().toString());
            jTxtGiaTriThamSo.setText("" + thamSo.getValue());
            jCheckThamSo.setSelected(thamSo.isUse());
        }
    }//GEN-LAST:event_jcbThamSoItemStateChanged

    private void hienThiThongTinKhachSan(KhachSan khachSan)
    {
        this.jtxtTen.setText(khachSan.getTen());
        this.jTxtWebsite.setText(khachSan.getWebsite());
        this.jTxtEmail.setText(khachSan.getEmail());
        this.jTxtDiaChi.setText(khachSan.getDiaChi());
        this.jFtxtDienThoai.setText(khachSan.getDienThoai());
        this.jFtxtFax.setText(khachSan.getFax());        
    }

    private void jBtnLuuMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLuuMouseReleased
        // TODO add your handling code here:
        if(!this.jBtnLuu.isEnabled())
            return;

        int result = JOptionPane.showConfirmDialog(this.getComponent(0),"Bạn có muốn lưu những thay đổi không?" , "Thông Báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION)
        {
            KhachSan tmp = new KhachSan();
            tmp.setId(khachSan.getId());
            tmp.setDiaChi(this.jTxtDiaChi.getText());
            tmp.setDienThoai(this.jFtxtDienThoai.getText());
            tmp.setEmail(this.jTxtEmail.getText());
            tmp.setFax(this.jFtxtFax.getText());
            tmp.setWebsite(this.jTxtWebsite.getText());
            tmp.setTen(this.jtxtTen.getText());

            if(khachSanController.capNhatKhachSan(tmp))
            {
                JOptionPane.showMessageDialog(this.getComponent(0),"Cập nhật thành công" , "Thông Báo", JOptionPane.INFORMATION_MESSAGE);
           }
            else
            {
                 JOptionPane.showMessageDialog(this.getComponent(0),"Cập nhật thông tin khách sạn thất bại" , "Thông báo", JOptionPane.ERROR_MESSAGE);
            }
        }
        else
        {
            hienThiThongTinKhachSan(khachSan);
        }


        this.jBtnLuu.setEnabled(false);
        this.jtxtTen.setEditable(false);
        this.jTxtWebsite.setEditable(false);
        this.jTxtEmail.setEditable(false);
        this.jTxtDiaChi.setEditable(false);
        this.jFtxtDienThoai.setEditable(false);
        this.jFtxtFax.setEditable(false);

        this.jBtnSua.setEnabled(true);

    }//GEN-LAST:event_jBtnLuuMouseReleased

    private void jBtnSuaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnSuaMouseReleased
        // TODO add your handling code here:
        if(!this.jBtnSua.isEnabled())
            return;

        int result = JOptionPane.showConfirmDialog(this.getComponent(0),"Bạn có muốn sửa không?" , "Thông Báo", JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.OK_OPTION)
        {
            //set editable
            this.jBtnLuu.setEnabled(true);
            this.jtxtTen.setEditable(true);
            this.jTxtWebsite.setEditable(true);
            this.jTxtEmail.setEditable(true);
            this.jTxtDiaChi.setEditable(true);
            this.jFtxtDienThoai.setEditable(true);
            this.jFtxtFax.setEditable(true);

            this.jBtnSua.setEnabled(false);
        }
    }//GEN-LAST:event_jBtnSuaMouseReleased

    private void initComboLoaiPhong() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        int i;
        for(i=0;i<this.lstGiaLoaiPhong.size();i++)
        {
            model.addElement(lstGiaLoaiPhong.get(i).getTenLoaiPhong());
        }

        jCbLoaiPhong.setModel(model);

        jCbLoaiPhong.setSelectedIndex(0);
        jTxtGiaPhong.setText("" + lstGiaLoaiPhong.get(0).getDonGiaPhong());
    }

    private void initComboLoaiKhachHang() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        int i;
        for(i=0;i<lstLoaiKhachHang.size();i++)
        {
            model.addElement(lstLoaiKhachHang.get(i).getTenLoaiKhachHang());
        }

        jCbLoaiKhach.setModel(model);

        jCbLoaiKhach.setSelectedIndex(0);
        jTxtGiaKhach.setText("" + lstLoaiKhachHang.get(0).getDonGiaKhachHang());
    }

    private void initComboThamSo() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        
        int i;
        for(i=0;i<lstThamSo.size();i++)
        {
            model.addElement(lstThamSo.get(i).getName());            
        }

        jcbThamSo.setModel(model);
        
        jcbThamSo.setSelectedIndex(0);
        ThamSo ts = lstThamSo.get(0);
        jTxtGiaTriThamSo.setText("" + ts.getValue());
        jCheckThamSo.setSelected(ts.isUse());
    }

    private KhachHang layLoaiKhachHangTheoTen(String ten)
    {
        int i;
        for(i=0;i<lstLoaiKhachHang.size();i++)
        {
            if(lstLoaiKhachHang.get(i).getTenLoaiKhachHang().equals(ten))
            {
                return lstLoaiKhachHang.get(i);
            }
        }
        return null;
    }

    private ThamSo layThamSoTheoTen(String tenThamSo)
    {
        int i;
        for(i=0;i<lstThamSo.size();i++)
        {
            if(lstThamSo.get(i).getName().equals(tenThamSo))
            {
                return lstThamSo.get(i);
            }
        }
        return null;
    }

    private Phong layGiaLoaiPhongTheoTen(String ten) {
        int i;
        for(i=0;i<this.lstGiaLoaiPhong.size();i++)
        {
            if(lstGiaLoaiPhong.get(i).getTenLoaiPhong().equals(ten))
            {
                return lstGiaLoaiPhong.get(i);
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel;
    private javax.swing.JLabel bgLabel1;
    private javax.swing.JLabel bgLabel2;
    private javax.swing.JLabel imgConfig;
    private javax.swing.JButton jBtnCapNhat;
    private javax.swing.JButton jBtnChinhSua;
    private javax.swing.JButton jBtnLuu;
    private javax.swing.JButton jBtnSua;
    private javax.swing.JComboBox jCbLoaiKhach;
    private javax.swing.JComboBox jCbLoaiPhong;
    private javax.swing.JCheckBox jCheckThamSo;
    private javax.swing.JFormattedTextField jFtxtDienThoai;
    private javax.swing.JFormattedTextField jFtxtFax;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jMainPanelHeThong;
    private javax.swing.JPanel jMainPanelNghiepVu;
    private javax.swing.JPanel jPanelHeThong;
    private javax.swing.JPanel jPanelNghiepVu;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTxtDiaChi;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JFormattedTextField jTxtGiaKhach;
    private javax.swing.JFormattedTextField jTxtGiaPhong;
    private javax.swing.JFormattedTextField jTxtGiaTriThamSo;
    private javax.swing.JTextField jTxtWebsite;
    private javax.swing.JComboBox jcbThamSo;
    private javax.swing.JTextField jtxtTen;
    // End of variables declaration//GEN-END:variables

    PhongController phongController;
    KhachHangController khachController;
    ThamSoController thamSoController;
    KhachSanController khachSanController;

    ArrayList<Phong> lstGiaLoaiPhong;    
    ArrayList<KhachHang> lstLoaiKhachHang;
    ArrayList<ThamSo> lstThamSo;

    private KhachSan khachSan;

}
class WorkerGetListThamSo extends SwingWorker<ArrayList<ThamSo>, Void>
{
    private ThamSoController thamSoController;
    @Override
    protected ArrayList<ThamSo> doInBackground() throws Exception {

        thamSoController = new ThamSoController();
        return thamSoController.layDSThamSo();
    }

}