/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JDialogXemChiTiet.java
 *
 * Created on Dec 24, 2009, 12:32:35 AM
 */

package client;

import DTO.Phong;
import javax.swing.JOptionPane;

/**
 *
 * @author bin
 */
public class JDialogXemChiTiet extends javax.swing.JDialog {

    private Phong phong;
    /** Creates new form JDialogXemChiTiet */
    public JDialogXemChiTiet(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public JDialogXemChiTiet(Phong phong) {
        super();
        initComponents();

        this.phong = phong;

        //init
        //this.jTxtLoaiPhong.setText(phong.getIdLoaiPhong().getTen());
        //this.jTxtMoTa.setText(phong.getMoTa());
       // this.jTxtSoPhong.setText(phong.getId());

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabelHinhPhong1 = new javax.swing.JLabel();
        jLabelGiaTien1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtSoPhong1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtLau1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtLoaiPhong1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTxtMoTa1 = new javax.swing.JTextArea();
        jBtnThoat = new javax.swing.JButton();
        jBtnCapNhat = new javax.swing.JButton();
        jBtnChinhSua = new javax.swing.JButton();
        jBtnThuePhong = new javax.swing.JButton();
        jTxtGiaTien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bgLabel4 = new javax.swing.JLabel();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JDialogXemChiTiet.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setIconImage(null);
        setMinimumSize(new java.awt.Dimension(179, 80));
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.GridBagLayout());

        jLabelHinhPhong1.setIcon(resourceMap.getIcon("jLabelHinhPhong1.icon")); // NOI18N
        jLabelHinhPhong1.setName("jLabelHinhPhong1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 18);
        jPanel8.add(jLabelHinhPhong1, gridBagConstraints);

        jLabelGiaTien1.setText(resourceMap.getString("jLabelGiaTien1.text")); // NOI18N
        jLabelGiaTien1.setName("jLabelGiaTien1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabelGiaTien1, gridBagConstraints);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabel4, gridBagConstraints);

        jTxtSoPhong1.setBackground(resourceMap.getColor("jTxtSoPhong1.background")); // NOI18N
        jTxtSoPhong1.setColumns(10);
        jTxtSoPhong1.setEditable(false);
        jTxtSoPhong1.setName("jTxtSoPhong1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtSoPhong1, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabel2, gridBagConstraints);

        jTxtLau1.setBackground(resourceMap.getColor("jTxtLau1.background")); // NOI18N
        jTxtLau1.setName("jTxtLau1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtLau1, gridBagConstraints);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jLabel6, gridBagConstraints);

        jTxtLoaiPhong1.setBackground(resourceMap.getColor("jTxtLoaiPhong1.background")); // NOI18N
        jTxtLoaiPhong1.setEditable(false);
        jTxtLoaiPhong1.setName("jTxtLoaiPhong1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtLoaiPhong1, gridBagConstraints);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 3;
        gridBagConstraints.ipady = 1;
        gridBagConstraints.insets = new java.awt.Insets(11, 10, 85, 10);
        jPanel8.add(jLabel8, gridBagConstraints);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTxtMoTa1.setBackground(resourceMap.getColor("jTxtMoTa1.background")); // NOI18N
        jTxtMoTa1.setColumns(20);
        jTxtMoTa1.setEditable(false);
        jTxtMoTa1.setRows(5);
        jTxtMoTa1.setName("jTxtMoTa1"); // NOI18N
        jScrollPane2.setViewportView(jTxtMoTa1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jScrollPane2, gridBagConstraints);

        jBtnThoat.setText(resourceMap.getString("jBtnThoat.text")); // NOI18N
        jBtnThoat.setName("jBtnThoat"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel8.add(jBtnThoat, gridBagConstraints);

        jBtnCapNhat.setText(resourceMap.getString("jBtnCapNhat.text")); // NOI18N
        jBtnCapNhat.setEnabled(false);
        jBtnCapNhat.setName("jBtnCapNhat"); // NOI18N
        jBtnCapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnCapNhatMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        jPanel8.add(jBtnCapNhat, gridBagConstraints);

        jBtnChinhSua.setText(resourceMap.getString("jBtnChinhSua.text")); // NOI18N
        jBtnChinhSua.setName("jBtnChinhSua"); // NOI18N
        jBtnChinhSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnChinhSuaMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel8.add(jBtnChinhSua, gridBagConstraints);

        jBtnThuePhong.setText(resourceMap.getString("jBtnThuePhong.text")); // NOI18N
        jBtnThuePhong.setName("jBtnThuePhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        jPanel8.add(jBtnThuePhong, gridBagConstraints);

        jTxtGiaTien.setBackground(resourceMap.getColor("jTxtGiaTien.background")); // NOI18N
        jTxtGiaTien.setText(resourceMap.getString("jTxtGiaTien.text")); // NOI18N
        jTxtGiaTien.setName("jTxtGiaTien"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel8.add(jTxtGiaTien, gridBagConstraints);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 4;
        jPanel8.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(jPanel8, gridBagConstraints);

        bgLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel4.setIcon(resourceMap.getIcon("bgLabel4.icon")); // NOI18N
        bgLabel4.setName("bgLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(bgLabel4, gridBagConstraints);

        getContentPane().add(jPanel7, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCapNhatMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnCapNhatMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnCapNhatMousePressed

    private void jBtnChinhSuaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnChinhSuaMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnChinhSuaMousePressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogXemChiTiet dialog = new JDialogXemChiTiet(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel4;
    private javax.swing.JButton jBtnCapNhat;
    private javax.swing.JButton jBtnChinhSua;
    private javax.swing.JButton jBtnThoat;
    private javax.swing.JButton jBtnThuePhong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelGiaTien1;
    private javax.swing.JLabel jLabelHinhPhong1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTxtGiaTien;
    private javax.swing.JTextField jTxtLau1;
    private javax.swing.JTextField jTxtLoaiPhong1;
    private javax.swing.JTextArea jTxtMoTa1;
    private javax.swing.JTextField jTxtSoPhong1;
    // End of variables declaration//GEN-END:variables

}