/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelThuePhong.java
 *
 * Created on Dec 18, 2009, 11:47:15 AM
 */

package client;

import BUS.KhachHangController;
import BUS.PhongController;
import BUS.ThuePhongController;
import DTO.KhachHang;
import DTO.LoaiKhachHang;
import DTO.LoaiThue;
import DTO.Phong;
import DTO.ThuePhong;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author huy
 */
public class JPanelThuePhong extends javax.swing.JPanel {
    private int SO_NGUOI_CU_TRU_TOI_DA = 3;

    /** Creates new form JPanelThuePhong */
    public JPanelThuePhong() {
        initComponents();

        khachController = new KhachHangController();
        thuePhongController = new ThuePhongController();
        phongController = new PhongController();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jTxtTenKhach = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTxtNgaySinh = new javax.swing.JFormattedTextField();
        jLabel31 = new javax.swing.JLabel();
        jCbGioiTinh = new javax.swing.JComboBox();
        jLabel32 = new javax.swing.JLabel();
        jTxtDiaChi = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTxtDienThoai = new javax.swing.JFormattedTextField();
        jLabel34 = new javax.swing.JLabel();
        jCbLoaiKhach = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jCbMaPhong = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jLabelLoaiPhong = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabelGiaTien = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jTxtNgayThue = new javax.swing.JFormattedTextField();
        jLabel43 = new javax.swing.JLabel();
        jCbSoNguoiCuTru = new javax.swing.JComboBox();
        jBtnThuePhong = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        imgCustomer = new javax.swing.JLabel();
        imgRoom = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lLabelLau = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCbLoaiThue = new javax.swing.JComboBox();
        bgLabel3 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.CardLayout());

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelThuePhong.class);
        jLabel27.setFont(resourceMap.getFont("jLabel27.font")); // NOI18N
        jLabel27.setForeground(resourceMap.getColor("jLabel27.foreground")); // NOI18N
        jLabel27.setText(resourceMap.getString("jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jLabel27, gridBagConstraints);

        jLabel29.setText(resourceMap.getString("jLabel29.text")); // NOI18N
        jLabel29.setName("jLabel29"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 17);
        jPanel2.add(jLabel29, gridBagConstraints);

        jTxtTenKhach.setBackground(resourceMap.getColor("jTxtTenKhach.background")); // NOI18N
        jTxtTenKhach.setColumns(80);
        jTxtTenKhach.setToolTipText(resourceMap.getString("jTxtTenKhach.toolTipText")); // NOI18N
        jTxtTenKhach.setName("jTxtTenKhach"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jTxtTenKhach, gridBagConstraints);

        jLabel30.setText(resourceMap.getString("jLabel30.text")); // NOI18N
        jLabel30.setName("jLabel30"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 44);
        jPanel2.add(jLabel30, gridBagConstraints);

        jTxtNgaySinh.setBackground(resourceMap.getColor("jTxtNgaySinh.background")); // NOI18N
        jTxtNgaySinh.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jTxtNgaySinh.setToolTipText(resourceMap.getString("jTxtNgaySinh.toolTipText")); // NOI18N
        jTxtNgaySinh.setName("jTxtNgaySinh"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jTxtNgaySinh, gridBagConstraints);

        jLabel31.setText(resourceMap.getString("jLabel31.text")); // NOI18N
        jLabel31.setName("jLabel31"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 55);
        jPanel2.add(jLabel31, gridBagConstraints);

        jCbGioiTinh.setBackground(resourceMap.getColor("jCbGioiTinh.background")); // NOI18N
        jCbGioiTinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nu" }));
        jCbGioiTinh.setToolTipText(resourceMap.getString("jCbGioiTinh.toolTipText")); // NOI18N
        jCbGioiTinh.setName("jCbGioiTinh"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jCbGioiTinh, gridBagConstraints);

        jLabel32.setText(resourceMap.getString("jLabel32.text")); // NOI18N
        jLabel32.setName("jLabel32"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 59);
        jPanel2.add(jLabel32, gridBagConstraints);

        jTxtDiaChi.setBackground(resourceMap.getColor("jTxtDiaChi.background")); // NOI18N
        jTxtDiaChi.setToolTipText(resourceMap.getString("jTxtDiaChi.toolTipText")); // NOI18N
        jTxtDiaChi.setName("jTxtDiaChi"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jTxtDiaChi, gridBagConstraints);

        jLabel33.setText(resourceMap.getString("jLabel33.text")); // NOI18N
        jLabel33.setName("jLabel33"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 42);
        jPanel2.add(jLabel33, gridBagConstraints);

        jTxtDienThoai.setBackground(resourceMap.getColor("jTxtDienThoai.background")); // NOI18N
        jTxtDienThoai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        jTxtDienThoai.setToolTipText(resourceMap.getString("jTxtDienThoai.toolTipText")); // NOI18N
        jTxtDienThoai.setName("jTxtDienThoai"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jTxtDienThoai, gridBagConstraints);

        jLabel34.setText(resourceMap.getString("jLabel34.text")); // NOI18N
        jLabel34.setName("jLabel34"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 13);
        jPanel2.add(jLabel34, gridBagConstraints);

        jCbLoaiKhach.setBackground(resourceMap.getColor("jCbLoaiKhach.background")); // NOI18N
        jCbLoaiKhach.setToolTipText(resourceMap.getString("jCbLoaiKhach.toolTipText")); // NOI18N
        jCbLoaiKhach.setName("jCbLoaiKhach"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jCbLoaiKhach, gridBagConstraints);

        jLabel35.setFont(resourceMap.getFont("jLabel35.font")); // NOI18N
        jLabel35.setForeground(resourceMap.getColor("jLabel35.foreground")); // NOI18N
        jLabel35.setText(resourceMap.getString("jLabel35.text")); // NOI18N
        jLabel35.setName("jLabel35"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(32, 0, 2, 0);
        jPanel2.add(jLabel35, gridBagConstraints);

        jLabel37.setText(resourceMap.getString("jLabel37.text")); // NOI18N
        jLabel37.setName("jLabel37"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 40);
        jPanel2.add(jLabel37, gridBagConstraints);

        jCbMaPhong.setBackground(resourceMap.getColor("jCbMaPhong.background")); // NOI18N
        jCbMaPhong.setToolTipText(resourceMap.getString("jCbMaPhong.toolTipText")); // NOI18N
        jCbMaPhong.setName("jCbMaPhong"); // NOI18N
        jCbMaPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCbMaPhongItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jCbMaPhong, gridBagConstraints);

        jLabel38.setText(resourceMap.getString("jLabel38.text")); // NOI18N
        jLabel38.setName("jLabel38"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 36);
        jPanel2.add(jLabel38, gridBagConstraints);

        jLabelLoaiPhong.setText(resourceMap.getString("jLabelLoaiPhong.text")); // NOI18N
        jLabelLoaiPhong.setName("jLabelLoaiPhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jLabelLoaiPhong, gridBagConstraints);

        jLabel40.setText(resourceMap.getString("jLabel40.text")); // NOI18N
        jLabel40.setName("jLabel40"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 52);
        jPanel2.add(jLabel40, gridBagConstraints);

        jLabelGiaTien.setText(resourceMap.getString("jLabelGiaTien.text")); // NOI18N
        jLabelGiaTien.setName("jLabelGiaTien"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jLabelGiaTien, gridBagConstraints);

        jLabel42.setText(resourceMap.getString("jLabel42.text")); // NOI18N
        jLabel42.setName("jLabel42"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 37);
        jPanel2.add(jLabel42, gridBagConstraints);

        jTxtNgayThue.setBackground(resourceMap.getColor("jTxtNgayThue.background")); // NOI18N
        jTxtNgayThue.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jTxtNgayThue.setToolTipText(resourceMap.getString("jTxtNgayThue.toolTipText")); // NOI18N
        jTxtNgayThue.setName("jTxtNgayThue"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jTxtNgayThue, gridBagConstraints);

        jLabel43.setText(resourceMap.getString("jLabel43.text")); // NOI18N
        jLabel43.setName("jLabel43"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 16);
        jPanel2.add(jLabel43, gridBagConstraints);

        jCbSoNguoiCuTru.setBackground(resourceMap.getColor("jCbSoNguoiCuTru.background")); // NOI18N
        jCbSoNguoiCuTru.setToolTipText(resourceMap.getString("jCbSoNguoiCuTru.toolTipText")); // NOI18N
        jCbSoNguoiCuTru.setName("jCbSoNguoiCuTru"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jCbSoNguoiCuTru, gridBagConstraints);

        jBtnThuePhong.setText(resourceMap.getString("jBtnThuePhong.text")); // NOI18N
        jBtnThuePhong.setToolTipText(resourceMap.getString("jBtnThuePhong.toolTipText")); // NOI18N
        jBtnThuePhong.setName("jBtnThuePhong"); // NOI18N
        jBtnThuePhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnThuePhongMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 7;
        gridBagConstraints.insets = new java.awt.Insets(22, 100, 1, 100);
        jPanel2.add(jBtnThuePhong, gridBagConstraints);

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 36;
        jPanel2.add(jLabel1, gridBagConstraints);

        imgCustomer.setIcon(resourceMap.getIcon("imgCustomer.icon")); // NOI18N
        imgCustomer.setText(resourceMap.getString("imgCustomer.text")); // NOI18N
        imgCustomer.setName("imgCustomer"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 18, 0, 0);
        jPanel2.add(imgCustomer, gridBagConstraints);

        imgRoom.setIcon(resourceMap.getIcon("imgRoom.icon")); // NOI18N
        imgRoom.setText(resourceMap.getString("imgRoom.text")); // NOI18N
        imgRoom.setName("imgRoom"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 28);
        jPanel2.add(imgRoom, gridBagConstraints);

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 28, 0, 0);
        jPanel2.add(jLabel3, gridBagConstraints);

        lLabelLau.setText(resourceMap.getString("lLabelLau.text")); // NOI18N
        lLabelLau.setName("lLabelLau"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(lLabelLau, gridBagConstraints);

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 28, 2, 16);
        jPanel2.add(jLabel2, gridBagConstraints);

        jCbLoaiThue.setBackground(resourceMap.getColor("jCbLoaiThue.background")); // NOI18N
        jCbLoaiThue.setName("jCbLoaiThue"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(2, 0, 2, 0);
        jPanel2.add(jCbLoaiThue, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(jPanel2, gridBagConstraints);

        bgLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel3.setIcon(resourceMap.getIcon("bgLabel3.icon")); // NOI18N
        bgLabel3.setName("bgLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel7.add(bgLabel3, gridBagConstraints);

        add(jPanel7, "card3");
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        //lay danh sach loai khach hang
        int i;
        lstLoaiKhachHang = khachController.getDSLoaiKhachHang();
        if(lstLoaiKhachHang!=null)
        {
            initComboBoxLoaiKhachHang();
        }

        //lay so nguoi cu tru lon nhat va add vao commbobox
        for(i=1;i<=SO_NGUOI_CU_TRU_TOI_DA;i++)
        {
            jCbSoNguoiCuTru.addItem(i);
        }

        //lay danh sach phong chua thue va add vao combobox
        lstPhong = phongController.getDSPhongChuaThue();
        if(lstPhong!=null)
        {
            initComboBoxMaPhong();
        }

        //lay loai thue va add vao combobox
        lstLoaiThue = thuePhongController.layDSLoaiThue();
        if(lstLoaiThue!=null)
        {
            initComboBoxLoaiThue();
        }

        //khoi tao gia tri cho ngay thue bang voi ngay hien tai
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        jTxtNgayThue.setText(sdf.format(cal.getTime()));

    }//GEN-LAST:event_formComponentShown

    private void initComboBoxLoaiThue()
    {
        int i;
        //add item to combobox
        for(i=0;i<lstLoaiThue.size();i++)
        {
            jCbLoaiThue.addItem(lstLoaiThue.get(i).getLoai());
        }
    }

    private void initComboBoxLoaiKhachHang()
    {
        int i;
        //add item to combobox
        for(i=0;i<lstLoaiKhachHang.size();i++)
        {
            jCbLoaiKhach.addItem(lstLoaiKhachHang.get(i).getTen());
        }
    }

    private void initComboBoxMaPhong()
    {
        int i;
        for(i=0;i<lstPhong.size();i++)
            {
                jCbMaPhong.addItem(lstPhong.get(i).getId());                
            }
            
            jCbMaPhong.setSelectedIndex(0);
            hienThiThongTinPhong(lstPhong.get(0));
    }

    private void hienThiThongTinPhong(Phong phong)
    {
        this.jLabelLoaiPhong.setText(phong.getIdLoaiPhong().getTen());
        this.jLabelGiaTien.setText("" + phong.getGia());
        this.lLabelLau.setText("" + phong.getLau());
    }

    private void jBtnThuePhongMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThuePhongMousePressed
        // TODO add your handling code here:
        try
        {
            //lay thong tin khach hang
            KhachHang khach = new KhachHang();

            khach.setDiaChi(jTxtDiaChi.getText());
            khach.setDienThoai(jTxtDienThoai.getText());
            khach.setGioiTinh((String)jCbGioiTinh.getSelectedItem());
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            khach.setNgaySinh(sdf.parse(jTxtNgaySinh.getText()));
            khach.setTen(jTxtTenKhach.getText());
            LoaiKhachHang loaiKhachHang = layLoaiKhachHangTheoTen(jCbLoaiKhach.getSelectedItem().toString());
            khach.setIdLoaiKhachHang(loaiKhachHang);

            ThuePhong thuePhong = new ThuePhong();
            thuePhong.setIdLoaiThue(layLoaiThueTheoTen(jCbLoaiThue.getSelectedItem().toString()));
            thuePhong.setKhachHang(khach);
            thuePhong.setNgayThue(sdf.parse(jTxtNgayThue.getText()));
            thuePhong.setPhong(layPhongTheoId(Integer.parseInt(jCbMaPhong.getSelectedItem().toString())));

            String error = thuePhongController.tiepNhanViecThuePhong(thuePhong);
            if(error.equals(""))
            {
                JOptionPane.showConfirmDialog(this.getComponent(0),"Thue phong thanh cong!" , "Thong bao", JOptionPane.OK_OPTION, JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                JOptionPane.showConfirmDialog(this.getComponent(0),error , "Thong bao loi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
            }
        }
        catch(Exception ex)
        {
            JOptionPane.showConfirmDialog(this.getComponent(0),ex.getMessage() , "Thong bao loi", JOptionPane.OK_OPTION, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBtnThuePhongMousePressed

    private void jCbMaPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCbMaPhongItemStateChanged
        // TODO add your handling code here:
        Phong phong = layPhongTheoId(Integer.parseInt(jCbMaPhong.getSelectedItem().toString()));
        hienThiThongTinPhong(phong);
    }//GEN-LAST:event_jCbMaPhongItemStateChanged

    private LoaiThue layLoaiThueTheoTen(String ten)
    {
        int i;
        for(i=0;i<lstLoaiThue.size();i++)
        {
            if(lstLoaiThue.get(i).getLoai().equals(ten))
            {
                return lstLoaiThue.get(i);
            }
        }
        return null;
    }

    private LoaiKhachHang layLoaiKhachHangTheoTen(String ten)
    {
        int i;
        for(i=0;i<lstLoaiKhachHang.size();i++)
        {
            if(lstLoaiKhachHang.get(i).getTen().equals(ten))
            {
                return lstLoaiKhachHang.get(i);
            }
        }
        return null;
    }

    private Phong layPhongTheoId(int id)
    {
        int i;
        for(i=0;i<lstPhong.size();i++)
        {
            if(lstPhong.get(i).getId() == id)
            {
                return lstPhong.get(i);
            }
        }
        return null;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel3;
    private javax.swing.JLabel imgCustomer;
    private javax.swing.JLabel imgRoom;
    private javax.swing.JButton jBtnThuePhong;
    private javax.swing.JComboBox jCbGioiTinh;
    private javax.swing.JComboBox jCbLoaiKhach;
    private javax.swing.JComboBox jCbLoaiThue;
    private javax.swing.JComboBox jCbMaPhong;
    private javax.swing.JComboBox jCbSoNguoiCuTru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabelGiaTien;
    private javax.swing.JLabel jLabelLoaiPhong;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTextField jTxtDiaChi;
    private javax.swing.JFormattedTextField jTxtDienThoai;
    private javax.swing.JFormattedTextField jTxtNgaySinh;
    private javax.swing.JFormattedTextField jTxtNgayThue;
    private javax.swing.JTextField jTxtTenKhach;
    private javax.swing.JLabel lLabelLau;
    // End of variables declaration//GEN-END:variables

    private KhachHangController khachController;
    private ThuePhongController thuePhongController;
    private PhongController phongController;

    private ArrayList<LoaiKhachHang> lstLoaiKhachHang;
    private ArrayList<Phong> lstPhong;
    private ArrayList<LoaiThue> lstLoaiThue;
}
