/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelThuePhong.java
 *
 * Created on Dec 18, 2009, 11:47:15 AM
 */

package client;

/**
 *
 * @author huy
 */
public class JPanelThuePhong extends javax.swing.JPanel {

    /** Creates new form JPanelThuePhong */
    public JPanelThuePhong() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneThuePhong = new javax.swing.JSplitPane();
        jLabel12 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel17 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel26 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jBtnThoat_ThuePhong = new javax.swing.JButton();
        jBtnThuePhong_ThuePhong = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 1));

        jPaneThuePhong.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jPaneThuePhong.setName("jPaneThuePhong"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelThuePhong.class);
        jLabel12.setFont(resourceMap.getFont("jLabel12.font")); // NOI18N
        jLabel12.setForeground(resourceMap.getColor("jLabel12.foreground")); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jPaneThuePhong.setLeftComponent(jLabel12);

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.GridLayout(14, 2, 5, 5));

        jLabel9.setFont(resourceMap.getFont("jLabel9.font")); // NOI18N
        jLabel9.setForeground(resourceMap.getColor("jLabel9.foreground")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jPanel6.add(jLabel9);

        jLabel10.setEnabled(false);
        jLabel10.setName("jLabel10"); // NOI18N
        jPanel6.add(jLabel10);

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jPanel6.add(jLabel11);

        jTextField2.setBackground(resourceMap.getColor("jTextField2.background")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        jPanel6.add(jTextField2);

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jPanel6.add(jLabel13);

        jFormattedTextField1.setBackground(resourceMap.getColor("jFormattedTextField1.background")); // NOI18N
        jFormattedTextField1.setName("jFormattedTextField1"); // NOI18N
        jPanel6.add(jFormattedTextField1);

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jPanel6.add(jLabel14);

        jComboBox1.setBackground(resourceMap.getColor("jComboBox3.background")); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nu" }));
        jComboBox1.setName("jComboBox1"); // NOI18N
        jPanel6.add(jComboBox1);

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N
        jPanel6.add(jLabel15);

        jTextField3.setBackground(resourceMap.getColor("jFormattedTextField3.background")); // NOI18N
        jTextField3.setName("jTextField3"); // NOI18N
        jPanel6.add(jTextField3);

        jLabel16.setText(resourceMap.getString("jLabel16.text")); // NOI18N
        jLabel16.setName("jLabel16"); // NOI18N
        jPanel6.add(jLabel16);

        jFormattedTextField2.setBackground(resourceMap.getColor("jFormattedTextField3.background")); // NOI18N
        jFormattedTextField2.setName("jFormattedTextField2"); // NOI18N
        jPanel6.add(jFormattedTextField2);

        jLabel17.setText(resourceMap.getString("jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel6.add(jLabel17);

        jComboBox2.setBackground(resourceMap.getColor("jComboBox3.background")); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Trong nuoc", "Nuoc ngoai" }));
        jComboBox2.setName("jComboBox2"); // NOI18N
        jPanel6.add(jComboBox2);

        jLabel18.setFont(resourceMap.getFont("jLabel18.font")); // NOI18N
        jLabel18.setForeground(resourceMap.getColor("jLabel18.foreground")); // NOI18N
        jLabel18.setText(resourceMap.getString("jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        jPanel6.add(jLabel18);

        jLabel19.setName("jLabel19"); // NOI18N
        jPanel6.add(jLabel19);

        jLabel20.setText(resourceMap.getString("jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jPanel6.add(jLabel20);

        jComboBox3.setBackground(resourceMap.getColor("jComboBox3.background")); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setName("jComboBox3"); // NOI18N
        jPanel6.add(jComboBox3);

        jLabel21.setText(resourceMap.getString("jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jPanel6.add(jLabel21);

        jLabel22.setText(resourceMap.getString("jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jPanel6.add(jLabel22);

        jLabel23.setText(resourceMap.getString("jLabel23.text")); // NOI18N
        jLabel23.setName("jLabel23"); // NOI18N
        jPanel6.add(jLabel23);

        jLabel24.setText(resourceMap.getString("jLabel24.text")); // NOI18N
        jLabel24.setName("jLabel24"); // NOI18N
        jPanel6.add(jLabel24);

        jLabel25.setText(resourceMap.getString("jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jPanel6.add(jLabel25);

        jFormattedTextField3.setBackground(resourceMap.getColor("jFormattedTextField3.background")); // NOI18N
        jFormattedTextField3.setName("jFormattedTextField3"); // NOI18N
        jPanel6.add(jFormattedTextField3);

        jLabel26.setText(resourceMap.getString("jLabel26.text")); // NOI18N
        jLabel26.setName("jLabel26"); // NOI18N
        jPanel6.add(jLabel26);

        jComboBox4.setBackground(resourceMap.getColor("jComboBox3.background")); // NOI18N
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3" }));
        jComboBox4.setName("jComboBox4"); // NOI18N
        jPanel6.add(jComboBox4);

        jBtnThoat_ThuePhong.setText(resourceMap.getString("jBtnThoat_ThuePhong.text")); // NOI18N
        jBtnThoat_ThuePhong.setName("jBtnThoat_ThuePhong"); // NOI18N
        jPanel6.add(jBtnThoat_ThuePhong);

        jBtnThuePhong_ThuePhong.setText(resourceMap.getString("jBtnThuePhong_ThuePhong.text")); // NOI18N
        jBtnThuePhong_ThuePhong.setName("jBtnThuePhong_ThuePhong"); // NOI18N
        jPanel6.add(jBtnThuePhong_ThuePhong);

        jPaneThuePhong.setRightComponent(jPanel6);

        add(jPaneThuePhong);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnThoat_ThuePhong;
    private javax.swing.JButton jBtnThuePhong_ThuePhong;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSplitPane jPaneThuePhong;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

}
