/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelTimPhong.java
 *
 * Created on Dec 18, 2009, 11:48:53 AM
 */

package client;

/**
 *
 * @author huy
 */
public class JPanelTimPhong extends javax.swing.JPanel {

    /** Creates new form JPanelTimPhong */
    public JPanelTimPhong() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneTimPhong = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jCheckMaPhong = new javax.swing.JCheckBox();
        jLabelMaPhong = new javax.swing.JLabel();
        jTxtMaPhong = new javax.swing.JTextField();
        jCheckLoaiPhong = new javax.swing.JCheckBox();
        jLabelLoaiPhong = new javax.swing.JLabel();
        jCbLoaiPhong = new javax.swing.JComboBox();
        jCheckTinhTrang = new javax.swing.JCheckBox();
        jLabelTinhTrang = new javax.swing.JLabel();
        jCbTinhTrang = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jBtnThoat = new javax.swing.JButton();
        jBtnTimKiem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 1));

        jPaneTimPhong.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jPaneTimPhong.setName("jPaneTimPhong"); // NOI18N

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelTimPhong.class);
        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jSplitPane1.setLeftComponent(jLabel3);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.GridLayout(4, 3, 5, 5));

        jCheckMaPhong.setText(resourceMap.getString("jCheckMaPhong.text")); // NOI18N
        jCheckMaPhong.setName("jCheckMaPhong"); // NOI18N
        jCheckMaPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckMaPhongItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckMaPhong);

        jLabelMaPhong.setText(resourceMap.getString("jLabelMaPhong.text")); // NOI18N
        jLabelMaPhong.setName("jLabelMaPhong"); // NOI18N
        jPanel1.add(jLabelMaPhong);

        jTxtMaPhong.setText(resourceMap.getString("jTxtMaPhong.text")); // NOI18N
        jTxtMaPhong.setName("jTxtMaPhong"); // NOI18N
        jPanel1.add(jTxtMaPhong);

        jCheckLoaiPhong.setText(resourceMap.getString("jCheckLoaiPhong.text")); // NOI18N
        jCheckLoaiPhong.setName("jCheckLoaiPhong"); // NOI18N
        jCheckLoaiPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckLoaiPhongItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckLoaiPhong);

        jLabelLoaiPhong.setText(resourceMap.getString("jLabelLoaiPhong.text")); // NOI18N
        jLabelLoaiPhong.setEnabled(false);
        jLabelLoaiPhong.setName("jLabelLoaiPhong"); // NOI18N
        jPanel1.add(jLabelLoaiPhong);

        jCbLoaiPhong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Binh thuong", "Dac biet", " " }));
        jCbLoaiPhong.setEnabled(false);
        jCbLoaiPhong.setName("jCbLoaiPhong"); // NOI18N
        jPanel1.add(jCbLoaiPhong);

        jCheckTinhTrang.setText(resourceMap.getString("jCheckTinhTrang.text")); // NOI18N
        jCheckTinhTrang.setName("jCheckTinhTrang"); // NOI18N
        jCheckTinhTrang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckTinhTrangItemStateChanged(evt);
            }
        });
        jPanel1.add(jCheckTinhTrang);

        jLabelTinhTrang.setText(resourceMap.getString("jLabelTinhTrang.text")); // NOI18N
        jLabelTinhTrang.setEnabled(false);
        jLabelTinhTrang.setName("jLabelTinhTrang"); // NOI18N
        jPanel1.add(jLabelTinhTrang);

        jCbTinhTrang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Con trong", "Da dat cho", "Dang sua chua" }));
        jCbTinhTrang.setEnabled(false);
        jCbTinhTrang.setName("jCbTinhTrang"); // NOI18N
        jPanel1.add(jCbTinhTrang);

        jLabel7.setName("jLabel7"); // NOI18N
        jPanel1.add(jLabel7);

        jBtnThoat.setText(resourceMap.getString("jBtnThoat.text")); // NOI18N
        jBtnThoat.setName("jBtnThoat"); // NOI18N
        jPanel1.add(jBtnThoat);

        jBtnTimKiem.setText(resourceMap.getString("jBtnTimKiem.text")); // NOI18N
        jBtnTimKiem.setName("jBtnTimKiem"); // NOI18N
        jPanel1.add(jBtnTimKiem);

        jSplitPane1.setRightComponent(jPanel1);

        jPanel4.add(jSplitPane1);

        jPaneTimPhong.setLeftComponent(jPanel4);

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.GridLayout(2, 1));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(78, 7));
        jLabel1.setMinimumSize(new java.awt.Dimension(78, 7));
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel5.add(jLabel1);

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Ma phong", "Loai phong", "Don gia", "Tinh trang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResult.setDoubleBuffered(true);
        jTableResult.setName("jTableResult"); // NOI18N
        jScrollPane1.setViewportView(jTableResult);

        jPanel5.add(jScrollPane1);

        jPaneTimPhong.setRightComponent(jPanel5);

        add(jPaneTimPhong);
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckLoaiPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckLoaiPhongItemStateChanged
        // TODO add your handling code here:
        if(jCheckLoaiPhong.isSelected())
        {
            jLabelLoaiPhong.setEnabled(true);
            jCbLoaiPhong.setEnabled(true);
        }
        else
        {
            jLabelLoaiPhong.setEnabled(false);
            jCbLoaiPhong.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckLoaiPhongItemStateChanged

    private void jCheckTinhTrangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckTinhTrangItemStateChanged
        // TODO add your handling code here:
        if(jCheckTinhTrang.isSelected())
        {
            jLabelTinhTrang.setEnabled(true);
            jCbTinhTrang.setEnabled(true);
        }
        else
        {
            jLabelTinhTrang.setEnabled(false);
            jCbTinhTrang.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckTinhTrangItemStateChanged

    private void jCheckMaPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckMaPhongItemStateChanged
        // TODO add your handling code here:
        if(jCheckMaPhong.isSelected())
        {
            jLabelMaPhong.setEnabled(true);
            jTxtMaPhong.setEnabled(true);
        }
        else
        {
            jLabelMaPhong.setEnabled(false);
            jTxtMaPhong.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckMaPhongItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnThoat;
    private javax.swing.JButton jBtnTimKiem;
    private javax.swing.JComboBox jCbLoaiPhong;
    private javax.swing.JComboBox jCbTinhTrang;
    private javax.swing.JCheckBox jCheckLoaiPhong;
    private javax.swing.JCheckBox jCheckMaPhong;
    private javax.swing.JCheckBox jCheckTinhTrang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLoaiPhong;
    private javax.swing.JLabel jLabelMaPhong;
    private javax.swing.JLabel jLabelTinhTrang;
    private javax.swing.JSplitPane jPaneTimPhong;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTableResult;
    private javax.swing.JTextField jTxtMaPhong;
    // End of variables declaration//GEN-END:variables

}
