/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelXemChiTiet.java
 *
 * Created on Dec 18, 2009, 11:47:58 AM
 */

package client;

/**
 *
 * @author huy
 */
public class JPanelXemChiTiet extends javax.swing.JPanel {

    /** Creates new form JPanelXemChiTiet */
    public JPanelXemChiTiet() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPaneXemChiTiet = new javax.swing.JSplitPane();
        jSplitPane4 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelHinhPhong_XemChiTiet = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabelGiaTien_XemChiTiet = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBtnThoat_XemChiTiet = new javax.swing.JButton();
        jBtnCapNhat_XemChiTiet = new javax.swing.JButton();
        jBtnChinhSua_XemChiTiet = new javax.swing.JButton();
        jBtnThuePhong_XemChiTiet = new javax.swing.JButton();

        setName("Form"); // NOI18N
        setLayout(new java.awt.GridLayout(1, 1));

        jPaneXemChiTiet.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jPaneXemChiTiet.setName("jPaneXemChiTiet"); // NOI18N

        jSplitPane4.setName("jSplitPane4"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(3, 1));

        jLabelHinhPhong_XemChiTiet.setIcon(null);
        jLabelHinhPhong_XemChiTiet.setName("jLabelHinhPhong_XemChiTiet"); // NOI18N
        jPanel2.add(jLabelHinhPhong_XemChiTiet);

        jSeparator3.setMaximumSize(new java.awt.Dimension(32767, 2));
        jSeparator3.setName("jSeparator3"); // NOI18N
        jPanel2.add(jSeparator3);

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelXemChiTiet.class);
        jLabelGiaTien_XemChiTiet.setText(resourceMap.getString("jLabelGiaTien_XemChiTiet.text")); // NOI18N
        jLabelGiaTien_XemChiTiet.setName("jLabelGiaTien_XemChiTiet"); // NOI18N
        jPanel2.add(jLabelGiaTien_XemChiTiet);

        jSplitPane4.setLeftComponent(jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(3, 2, 2, 2));

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jPanel3.add(jLabel3);

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jPanel3.add(jLabel4);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jPanel3.add(jLabel5);

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jPanel3.add(jLabel6);

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jPanel3.add(jLabel7);

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jPanel3.add(jLabel8);

        jSplitPane4.setRightComponent(jPanel3);

        jPaneXemChiTiet.setLeftComponent(jSplitPane4);

        jPanel1.setName("jPanel1"); // NOI18N

        jBtnThoat_XemChiTiet.setText(resourceMap.getString("jBtnThoat_XemChiTiet.text")); // NOI18N
        jBtnThoat_XemChiTiet.setName("jBtnThoat_XemChiTiet"); // NOI18N
        jBtnThoat_XemChiTiet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnThoat_XemChiTietMouseClicked(evt);
            }
        });
        jPanel1.add(jBtnThoat_XemChiTiet);

        jBtnCapNhat_XemChiTiet.setText(resourceMap.getString("jBtnCapNhat_XemChiTiet.text")); // NOI18N
        jBtnCapNhat_XemChiTiet.setEnabled(false);
        jBtnCapNhat_XemChiTiet.setName("jBtnCapNhat_XemChiTiet"); // NOI18N
        jPanel1.add(jBtnCapNhat_XemChiTiet);

        jBtnChinhSua_XemChiTiet.setText(resourceMap.getString("jBtnChinhSua_XemChiTiet.text")); // NOI18N
        jBtnChinhSua_XemChiTiet.setName("jBtnChinhSua_XemChiTiet"); // NOI18N
        jPanel1.add(jBtnChinhSua_XemChiTiet);

        jBtnThuePhong_XemChiTiet.setText(resourceMap.getString("jBtnThuePhong_XemChiTiet.text")); // NOI18N
        jBtnThuePhong_XemChiTiet.setName("jBtnThuePhong_XemChiTiet"); // NOI18N
        jPanel1.add(jBtnThuePhong_XemChiTiet);

        jPaneXemChiTiet.setRightComponent(jPanel1);

        add(jPaneXemChiTiet);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnThoat_XemChiTietMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnThoat_XemChiTietMouseClicked
        // TODO add your handling code here:        
}//GEN-LAST:event_jBtnThoat_XemChiTietMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCapNhat_XemChiTiet;
    private javax.swing.JButton jBtnChinhSua_XemChiTiet;
    private javax.swing.JButton jBtnThoat_XemChiTiet;
    private javax.swing.JButton jBtnThuePhong_XemChiTiet;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelGiaTien_XemChiTiet;
    private javax.swing.JLabel jLabelHinhPhong_XemChiTiet;
    private javax.swing.JSplitPane jPaneXemChiTiet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSplitPane jSplitPane4;
    // End of variables declaration//GEN-END:variables

}
