/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelXemPhong.java
 *
 * Created on Dec 18, 2009, 12:04:53 PM
 */

package client;

import BUS.PhongController;
import DTO.Phong;
import Utils.MyCompare;
import java.awt.GridBagConstraints;
import java.awt.Insets;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author huy
 */
public class JPanelXemPhong extends javax.swing.JPanel {
    private JFrame mainFrame;
    private int currentFloor;
    private ImageIcon iconPhongDaThue;
    private ImageIcon iconPhongConTrong;

    /** Creates new form JPanelXemPhong */
    public JPanelXemPhong(JFrame parent) {
        initComponents();

        this.mainFrame = parent;

        //set icon for button
        ClassLoader cldr = this.getClass().getClassLoader();
        java.net.URL imageURL;
        imageURL = cldr.getResource("client/resources/RoomAvailable.png");
        this.iconPhongConTrong = new ImageIcon(imageURL);

        imageURL = cldr.getResource("client/resources/RoomNotAvailable.png");
        this.iconPhongDaThue = new ImageIcon(imageURL);

        jSplitPane1.getTopComponent().setSize(686, 500);
        jSplitPane1.getBottomComponent().setSize(686, 100);

        //new cac doi tuong
        phongController = new PhongController();

        //lay ra lau cao nhat cua khach san
        maxFloor = phongController.getLauCaoNhat();

        //lay ra danh sach nhung phong hien co trong lau 1 va ve len panel
        if(maxFloor>0)
        {
            currentFloor = 1;
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jBtnPrev = new javax.swing.JButton();
        jLabelPageNumber = new javax.swing.JLabel();
        jBtnNext = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        bgLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanelView = new javax.swing.JPanel();
        bgLabel3 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.CardLayout());

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setName("jSplitPane1"); // NOI18N

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelXemPhong.class);
        jBtnPrev.setText(resourceMap.getString("jBtnPrev.text")); // NOI18N
        jBtnPrev.setEnabled(false);
        jBtnPrev.setName("jBtnPrev"); // NOI18N
        jBtnPrev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnPrevMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(jBtnPrev, gridBagConstraints);

        jLabelPageNumber.setText(resourceMap.getString("jLabelPageNumber.text")); // NOI18N
        jLabelPageNumber.setName("jLabelPageNumber"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jLabelPageNumber, gridBagConstraints);

        jBtnNext.setText(resourceMap.getString("jBtnNext.text")); // NOI18N
        jBtnNext.setName("jBtnNext"); // NOI18N
        jBtnNext.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnNextMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 13, 0, 13);
        jPanel1.add(jBtnNext, gridBagConstraints);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(jPanel1, gridBagConstraints);

        bgLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel1.setIcon(resourceMap.getIcon("bgLabel1.icon")); // NOI18N
        bgLabel1.setText(resourceMap.getString("bgLabel1.text")); // NOI18N
        bgLabel1.setName("bgLabel1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel2.add(bgLabel1, gridBagConstraints);

        jSplitPane1.setRightComponent(jPanel2);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanelView.setName("jPanelView"); // NOI18N
        jPanelView.setOpaque(false);
        jPanelView.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(jPanelView, gridBagConstraints);

        bgLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel3.setIcon(resourceMap.getIcon("bgLabel3.icon")); // NOI18N
        bgLabel3.setText(resourceMap.getString("bgLabel3.text")); // NOI18N
        bgLabel3.setName("bgLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel4.add(bgLabel3, gridBagConstraints);

        jSplitPane1.setLeftComponent(jPanel4);

        add(jSplitPane1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPrevMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnPrevMousePressed
        // TODO add your handling code here:
        int num = Integer.parseInt(jLabelPageNumber.getText());
        if(num>1)
        {            
            num--;
            if(num == 1)
            {
                jBtnPrev.setEnabled(false);
                jBtnNext.setEnabled(true);
            }
            else
            {
                jBtnPrev.setEnabled(true);
                jBtnNext.setEnabled(true);
            }

            repaintFloor(num);
            currentFloor = num;
            
            jLabelPageNumber.setText("" + num);
        }
    }//GEN-LAST:event_jBtnPrevMousePressed

    private void jBtnNextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnNextMousePressed
        // TODO add your handling code here:
        int num = Integer.parseInt(jLabelPageNumber.getText());
        if(num < maxFloor)
        {            
            num++;
            if(num == maxFloor)
            {
                jBtnPrev.setEnabled(true);
                jBtnNext.setEnabled(false);
            }
            else
            {
                jBtnPrev.setEnabled(true);
                jBtnNext.setEnabled(true);
            }

            repaintFloor(num);
            currentFloor = num;

            jLabelPageNumber.setText("" + num);
        }
    }//GEN-LAST:event_jBtnNextMousePressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        repaintFloor(currentFloor);
        
    }//GEN-LAST:event_formComponentShown

    private void jBtnPhongPress(MouseEvent evt) {
        JButton button = (JButton)evt.getComponent();
        if(button!=null)
        {
            //Phong tmp = timPhongTheoId(Integer.parseInt(button.getName()));
            int indexPhong = timIndexPhongTrongArr(Integer.parseInt(button.getName()));
            JDialogXemChiTiet xemChiTietFrm = new JDialogXemChiTiet(mainFrame, true, this.listPhong.get(indexPhong));
            xemChiTietFrm.setVisible(true);
            //cap nhat lai phong moi
            //this.listPhong.get(indexPhong).clone(xemChiTietFrm.getPhong());
            repaintFloor(currentFloor);
            this.repaint();
        }
    }

    private int timIndexPhongTrongArr(int id)
    {
        int i;
        for(i=0;i<listPhong.size();i++)
        {
            Phong tmp = listPhong.get(i);
            if(tmp.getId() == id)
                return i;
        }
        return -1;
    }

    public void repaintFloor(int numFloor)
    {
        //remove old buttons and labels
        jPanelView.removeAll();

        //lay danh sach cac phong co trong lau
        listPhong = phongController.getDSPhongTheoLau(numFloor);
        
        //add new buttons and labels
        int n = listPhong.size();
        int i;
        int t = 0;
        int d = 0;

        for(i=0;i<n;i++)
        {
            Phong phong = listPhong.get(i);

            JButton button = new JButton();
            button.setName("" + phong.getId());

            //set icon for button
            if(MyCompare.compareString(phong.getIdTinhTrang().getTen(), "Còn Trống") == 0)
            //if(phong.getIdTinhTrang().getTen().equals("Con trong"))
            {
                button.setIcon(iconPhongConTrong);
                button.setToolTipText("Phòng còn trống");
            }
            else
            {
                button.setIcon(iconPhongDaThue);
                button.setToolTipText("Phòng đã có người");
            }

            //set event listener for button
            button.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnPhongPress(evt);
            }
            });

            //set label for name of room
            JLabel label = new JLabel();
            label.setText("Mã Phòng: " + phong.getId());
            label.setName("" + phong.getId());
            label.setHorizontalTextPosition(JLabel.CENTER);
            label.setVerticalTextPosition(JLabel.CENTER);
            label.setHorizontalAlignment(JLabel.CENTER);

            label.setOpaque(false);

            //constraint for button
            GridBagConstraints cButton = new GridBagConstraints();
            //constraint for label
            GridBagConstraints cLabel = new GridBagConstraints();

            //set constraint for button and label
            cButton.fill = GridBagConstraints.BOTH;
            cButton.insets = new java.awt.Insets(5, 25, 5, 25);
            
            cLabel.fill = GridBagConstraints.BOTH;

            if(i%2==0)
            {
                //phong chan o duoi
                cButton.gridx = d;
                cButton.gridy = 2;

                cLabel.insets = new Insets(5,25,5,25);
                cLabel.gridx = d;
                cLabel.gridy = 3;

                d++;
            }
            else
            {
                //phong le ben tren
                cButton.gridx = t;
                cButton.gridy = 0;

                cLabel.insets = new Insets(5,25,15,25);
                cLabel.gridx = t;
                cLabel.gridy = 1;

                t++;
            }

            jPanelView.add(button, cButton);
            jPanelView.add(label, cLabel);
        }

        jPanelView.validate();
        this.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel1;
    private javax.swing.JLabel bgLabel3;
    private javax.swing.JButton jBtnNext;
    private javax.swing.JButton jBtnPrev;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelPageNumber;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelView;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
    
    private int maxFloor;
    private PhongController phongController;
    private ArrayList<Phong> listPhong;
}