/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelTimPhong.java
 *
 * Created on Dec 18, 2009, 11:48:53 AM
 */

package client;

import BUS.PhongController;
import DTO.Phong;
import DTO.TinhTrangPhong;
import java.util.ArrayList;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author huy
 */
public class JPanelTimPhong extends javax.swing.JPanel {

    /** Creates new form JPanelTimPhong */
    public JPanelTimPhong() {
        initComponents();
        
        phongController = new PhongController();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jCheckMaPhong = new javax.swing.JCheckBox();
        jLabelMaPhong1 = new javax.swing.JLabel();
        jCheckLoaiPhong = new javax.swing.JCheckBox();
        jLabelLoaiPhong1 = new javax.swing.JLabel();
        jCbLoaiPhong = new javax.swing.JComboBox();
        jCheckTinhTrang = new javax.swing.JCheckBox();
        jLabelTinhTrang1 = new javax.swing.JLabel();
        jCbTinhTrang = new javax.swing.JComboBox();
        jBtnTimKiem = new javax.swing.JButton();
        imgSearch1 = new javax.swing.JLabel();
        jTxtMaPhong = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableResult = new javax.swing.JTable();
        bgLabel4 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 1));

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.GridBagLayout());

        jPanel7.setAutoscrolls(true);
        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.GridBagLayout());

        jCheckMaPhong.setSelected(true);
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(client.ClientApp.class).getContext().getResourceMap(JPanelTimPhong.class);
        jCheckMaPhong.setText(resourceMap.getString("jCheckMaPhong.text")); // NOI18N
        jCheckMaPhong.setName("jCheckMaPhong"); // NOI18N
        jCheckMaPhong.setOpaque(false);
        jCheckMaPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckMaPhongItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jCheckMaPhong, gridBagConstraints);

        jLabelMaPhong1.setText(resourceMap.getString("jLabelMaPhong1.text")); // NOI18N
        jLabelMaPhong1.setName("jLabelMaPhong1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jLabelMaPhong1, gridBagConstraints);

        jCheckLoaiPhong.setText(resourceMap.getString("jCheckLoaiPhong.text")); // NOI18N
        jCheckLoaiPhong.setName("jCheckLoaiPhong"); // NOI18N
        jCheckLoaiPhong.setOpaque(false);
        jCheckLoaiPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckLoaiPhongItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jCheckLoaiPhong, gridBagConstraints);

        jLabelLoaiPhong1.setText(resourceMap.getString("jLabelLoaiPhong1.text")); // NOI18N
        jLabelLoaiPhong1.setEnabled(false);
        jLabelLoaiPhong1.setName("jLabelLoaiPhong1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jLabelLoaiPhong1, gridBagConstraints);

        jCbLoaiPhong.setBackground(resourceMap.getColor("jCbLoaiPhong.background")); // NOI18N
        jCbLoaiPhong.setEnabled(false);
        jCbLoaiPhong.setName("jCbLoaiPhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jCbLoaiPhong, gridBagConstraints);

        jCheckTinhTrang.setText(resourceMap.getString("jCheckTinhTrang.text")); // NOI18N
        jCheckTinhTrang.setName("jCheckTinhTrang"); // NOI18N
        jCheckTinhTrang.setOpaque(false);
        jCheckTinhTrang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCheckTinhTrangItemStateChanged(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jCheckTinhTrang, gridBagConstraints);

        jLabelTinhTrang1.setText(resourceMap.getString("jLabelTinhTrang1.text")); // NOI18N
        jLabelTinhTrang1.setEnabled(false);
        jLabelTinhTrang1.setName("jLabelTinhTrang1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jLabelTinhTrang1, gridBagConstraints);

        jCbTinhTrang.setBackground(resourceMap.getColor("jCbTinhTrang.background")); // NOI18N
        jCbTinhTrang.setEnabled(false);
        jCbTinhTrang.setName("jCbTinhTrang"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jCbTinhTrang, gridBagConstraints);

        jBtnTimKiem.setText(resourceMap.getString("jBtnTimKiem.text")); // NOI18N
        jBtnTimKiem.setName("jBtnTimKiem"); // NOI18N
        jBtnTimKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jBtnTimKiemMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.insets = new java.awt.Insets(20, 8, 8, 8);
        jPanel7.add(jBtnTimKiem, gridBagConstraints);

        imgSearch1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgSearch1.setName("imgSearch1"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        jPanel7.add(imgSearch1, gridBagConstraints);

        jTxtMaPhong.setBackground(resourceMap.getColor("jTxtMaPhong.background")); // NOI18N
        jTxtMaPhong.setColumns(15);
        jTxtMaPhong.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("0"))));
        jTxtMaPhong.setName("jTxtMaPhong"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(4, 8, 4, 8);
        jPanel7.add(jTxtMaPhong, gridBagConstraints);

        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLabel3.foreground")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel7.add(jLabel3, gridBagConstraints);

        jLabel4.setFont(resourceMap.getFont("jLabel4.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLabel4.foreground")); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(78, 7));
        jLabel4.setMinimumSize(new java.awt.Dimension(78, 7));
        jLabel4.setName("jLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(20, 0, 20, 0);
        jPanel7.add(jLabel4, gridBagConstraints);

        jScrollPane2.setName("jScrollPane2"); // NOI18N
        jScrollPane2.setPreferredSize(new java.awt.Dimension(452, 150));

        jTableResult.setAutoCreateRowSorter(true);
        jTableResult.setBackground(resourceMap.getColor("jTableResult.background")); // NOI18N
        jTableResult.setBorder(new javax.swing.border.MatteBorder(null));
        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", "", null, ""},
                {"", null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Phòng", "Loại Phòng", "Đơn Giá", "Tình Trạng"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableResult.setToolTipText(resourceMap.getString("jTableResult.toolTipText")); // NOI18N
        jTableResult.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableResult.setCellSelectionEnabled(true);
        jTableResult.setDoubleBuffered(true);
        jTableResult.setName("jTableResult"); // NOI18N
        jScrollPane2.setViewportView(jTableResult);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel7.add(jScrollPane2, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(jPanel7, gridBagConstraints);

        bgLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bgLabel4.setIcon(resourceMap.getIcon("bgLabel4.icon")); // NOI18N
        bgLabel4.setName("bgLabel4"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        jPanel6.add(bgLabel4, gridBagConstraints);

        add(jPanel6);
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        int i;

        //get ds loai phong
        WorkerGetListLoaiPhong worker = new WorkerGetListLoaiPhong();
        worker.execute();
        try {
            lstLoaiPhong = worker.get();
        } catch (InterruptedException ex) {
            Logger.getLogger(JPanelTimPhong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExecutionException ex) {
            Logger.getLogger(JPanelTimPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        //lstLoaiPhong = phongController.getDSLoaiPhong();
        if(lstLoaiPhong!=null)
        {
            jCbLoaiPhong.removeAllItems();

            for(i=0;i<lstLoaiPhong.size();i++)
            {
                jCbLoaiPhong.addItem(lstLoaiPhong.get(i));
            }
        }

        //get ds tinh trang phong
        WorkerGetListTinhTrangPhong workerTinhTrangPhong = new WorkerGetListTinhTrangPhong();
        workerTinhTrangPhong.execute();
        try {
            lstTinhTrangPhong = workerTinhTrangPhong.get();
        } catch (InterruptedException ex) {
            Logger.getLogger(JPanelTimPhong.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ExecutionException ex) {
            Logger.getLogger(JPanelTimPhong.class.getName()).log(Level.SEVERE, null, ex);
        }
        //lstTinhTrangPhong = phongController.getDSTinhTrangPhong();
        if(lstTinhTrangPhong!=null)
        {
            jCbTinhTrang.removeAllItems();

            for(i=0;i<lstTinhTrangPhong.size();i++)
            {
                jCbTinhTrang.addItem(lstTinhTrangPhong.get(i).getTen());
            }
        }
    }//GEN-LAST:event_formComponentShown

    private void jCheckMaPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckMaPhongItemStateChanged
        // TODO add your handling code here:
        if(jCheckMaPhong.isSelected())
        {
            jLabelMaPhong1.setEnabled(true);
            jTxtMaPhong.setEnabled(true);
        }
        else
        {
            jLabelMaPhong1.setEnabled(false);
            jTxtMaPhong.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckMaPhongItemStateChanged

    private void jCheckLoaiPhongItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckLoaiPhongItemStateChanged
        // TODO add your handling code here:
        if(jCheckLoaiPhong.isSelected())
        {
            jLabelLoaiPhong1.setEnabled(true);
            jCbLoaiPhong.setEnabled(true);
        }
        else
        {
            jLabelLoaiPhong1.setEnabled(false);
            jCbLoaiPhong.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckLoaiPhongItemStateChanged

    private void jCheckTinhTrangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckTinhTrangItemStateChanged
        // TODO add your handling code here:
        if(jCheckTinhTrang.isSelected())
        {
            jLabelTinhTrang1.setEnabled(true);
            jCbTinhTrang.setEnabled(true);
        }
        else
        {
            jLabelTinhTrang1.setEnabled(false);
            jCbTinhTrang.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckTinhTrangItemStateChanged

    private void jBtnTimKiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnTimKiemMousePressed
        // TODO add your handling code here:
        if(!jCheckLoaiPhong.isSelected() && !jCheckMaPhong.isSelected() && !jCheckTinhTrang.isSelected())
        {
            JOptionPane.showMessageDialog(this.getComponent(0),"Hãy nhập vào điều kiện tìm kiếm!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if(jCheckMaPhong.isSelected() && jTxtMaPhong.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this.getComponent(0),"Hãy nhập vào mã phòng cần tìm!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sLoaiPhong = "";
        if(jCheckLoaiPhong.isSelected())
        {
            sLoaiPhong = timLoaiPhongTheoTen(jCbLoaiPhong.getSelectedItem().toString());
        }

        int idTinhTrang = -1;
        if(jCheckTinhTrang.isSelected())
        {
            idTinhTrang = timTinhTrangPhongTheoTen(jCbTinhTrang.getSelectedItem().toString()).getId();
        }

        int idPhong = -1;
        if(jCheckMaPhong.isSelected())
        {
            String s = jTxtMaPhong.getText();
            if(!s.equals(""))
            {
                idPhong = Integer.parseInt(s);
                if(idPhong<0)
                {
                    JOptionPane.showMessageDialog(this.getComponent(0),"Mã phòng nhập sai!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }
        

        ArrayList<Phong> lst = phongController.timPhong(idPhong, sLoaiPhong, idTinhTrang);
        if(lst!=null)
        {
            if(lst.size()==0)
            {
                JOptionPane.showMessageDialog(this.getComponent(0),"Không tìm thấy kết quả", "Thông Báo", JOptionPane.INFORMATION_MESSAGE);

                //clear table data
                DefaultTableModel model = new DefaultTableModel(headerTable, 0);
                jTableResult.setModel(model);
            }
            else
            {
                hienThiDanhSachPhong(lst);
            }
        }
    }//GEN-LAST:event_jBtnTimKiemMousePressed
    
    private void hienThiDanhSachPhong(ArrayList<Phong> lst)
    {
        jTableResult.setModel(new javax.swing.table.DefaultTableModel(
            headerTable,0
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });

        DefaultTableModel model = (DefaultTableModel) jTableResult.getModel();

        int i;
        for(i=0;i<lst.size();i++)
        {
            Object[] arr = new Object[4];

            Phong phong = lst.get(i);
            arr[0] = phong.getId();
            arr[1] = phong.getTenLoaiPhong();//.getIdLoaiPhong().getTen();
            arr[2] = phong.getGia() + phong.getDonGiaPhong();//.getIdLoaiPhong().getGia();
            arr[3] = phong.getIdTinhTrang().getTen();

            model.addRow(arr);
        }
    }

    private TinhTrangPhong timTinhTrangPhongTheoTen(String ten)
    {
        int i;
        for(i=0;i<lstTinhTrangPhong.size();i++)
        {
            if(lstTinhTrangPhong.get(i).getTen().equals(ten))
            {
                return lstTinhTrangPhong.get(i);
            }
        }
        return null;
    }

    private String timLoaiPhongTheoTen(String ten)
    {
        int i;
        for(i=0;i<lstLoaiPhong.size();i++)
        {
            if(lstLoaiPhong.get(i).equals(ten))
            {
                return lstLoaiPhong.get(i);
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLabel4;
    private javax.swing.JLabel imgSearch1;
    private javax.swing.JButton jBtnTimKiem;
    private javax.swing.JComboBox jCbLoaiPhong;
    private javax.swing.JComboBox jCbTinhTrang;
    private javax.swing.JCheckBox jCheckLoaiPhong;
    private javax.swing.JCheckBox jCheckMaPhong;
    private javax.swing.JCheckBox jCheckTinhTrang;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelLoaiPhong1;
    private javax.swing.JLabel jLabelMaPhong1;
    private javax.swing.JLabel jLabelTinhTrang1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableResult;
    private javax.swing.JFormattedTextField jTxtMaPhong;
    // End of variables declaration//GEN-END:variables

    private PhongController phongController;
    private ArrayList<String> lstLoaiPhong;
    private ArrayList<TinhTrangPhong> lstTinhTrangPhong;
    private String[] headerTable = new String [] {
                "Mã Phòng", "Loại Phòng", "Đơn Giá", "Tình Trạng"
            };
}

class WorkerGetListLoaiPhong extends SwingWorker<ArrayList<String>, Void>
{
    private PhongController phongController;

    @Override
    protected ArrayList<String> doInBackground() throws Exception {

        phongController = new PhongController();
        return phongController.getDSLoaiPhong();
    }
}

class WorkerGetListTinhTrangPhong extends SwingWorker<ArrayList<TinhTrangPhong>, Void>
{
    private PhongController phongController;

    @Override
    protected ArrayList<TinhTrangPhong> doInBackground() throws Exception {

        phongController = new PhongController();
        return phongController.getDSTinhTrangPhong();

    }

}
